---
title: "to 2015"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)

```

```{r}

rats <- read.csv(here::here("lore", "2020_redux", "christensen_plots.csv"))

```

```{r}

rats_types_totals <- rats %>%
  mutate(plot = factor(plot),
         treatment = factor(treatment)) %>%
  #mutate(plot = as.ordered(plot),
 #        treatment = as.ordered(treatment)) %>%
  select(period, treatment, type, plot, energy) %>%
  group_by(period, treatment, type, plot) %>%
  summarize(nind = dplyr::n(),
            totale = sum(energy))  %>%
  ungroup() 

rats_totals <- rats %>% 
  mutate(plot = factor(plot),
         treatment = factor(treatment)) %>%
  select(period, treatment, plot, energy) %>%
  group_by(period, treatment, plot) %>%
  summarize(nind = dplyr::n(),
            totale = sum(energy)) %>%
  ungroup() 

```

```{r}
ggplot(filter(rats_totals), aes(period, nind, color = treatment, group = plot)) +
 geom_smooth(method = "gam", se = F, size = 2) +  theme_bw() +
  scale_color_viridis_d(end = .8) 
ggplot(filter(rats_totals), aes(period, totale, color = treatment, group = plot)) +
 geom_smooth(method = "gam", se = F, size = 2) +  theme_bw() +
  scale_color_viridis_d(end = .8) 

```

```{r}

th_per1 <- filter(rats_totals, period >= 118, period < 216) %>%
  group_by(period, treatment) %>%
    summarize(totale = sum(totale, na.rm = T)) %>%ungroup()%>%
  mutate(era= "th1")

th_per2 <- filter(rats_totals, period >= 216, period < 356)%>%
  group_by(period, treatment) %>%  summarize(totale = sum(totale, na.rm = T)) %>%
  ungroup() %>%
  mutate(era = "th2")
 
since_th <- filter(rats_totals, period >= 356, period < 434) %>%
    group_by(period, treatment) %>%  summarize(totale = sum(totale, na.rm = T)) %>%ungroup() %>%
  mutate(era = "now")

ggplot(th_per1, aes(period, totale, color = treatment)) +
  geom_line()

ggplot(th_per2, aes(period, totale, color = treatment)) +
  geom_line()


ggplot(since_th, aes(period, totale, color = treatment)) +
  geom_line()

alltime <- bind_rows(th_per1, th_per2, since_th)

alltime_wide <- alltime %>%
  tidyr::pivot_wider(id_cols = c(period, era), names_from = treatment, values_from = totale)

ttest1 <- t.test(filter(alltime_wide, era == "th1")$CC, filter(alltime_wide, era == "th1")$EC)

ttest1

ttest2 <- t.test(filter(alltime_wide, era == "th2")$CC, filter(alltime_wide, era == "th2")$EC)

ttest2

ttest3 <- t.test(filter(alltime_wide, era == "now")$CC, filter(alltime_wide, era == "now")$EC)
ttest3

ggplot(alltime_wide, aes(period, EC / CC, color = era)) +
  geom_line() #+
  #  geom_line(data = nd.wide, aes(period, ratio), color = "pink")


```






```{r}

library(lme4)

eras <- alltime %>%
  select(period, era) %>%
  distinct() %>%
  right_join(rats_totals)

#a_lme <- lmer(totale ~ era * treatment + (1 | plot), data = eras)

#eras$fitted <- fitted(a_lme)
```

<!-- ```{r} -->

<!-- library(strucchange) -->

<!-- a_bp <- breakpoints(totale ~ 1 + treatment, data = eras) -->

<!-- plot(alltime_ratio$ratio) -->

<!-- plot(fitted(a_bp)) -->

<!-- ``` -->

```{r}

a.lme <- nlme::lme(fixed = totale ~ period, data = rats_totals, na.action = na.exclude)

```
