---
title: "body size overlap"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r}

ratcounts <- portalr::abundance(level = "Site", type = "Granivores", time = "censusdate")


corerats <- ratcounts %>%
  select(censusdate, DM, DO, DS, PB, PP) %>%
  tidyr::pivot_longer(-censusdate, names_to = "species", values_to = "abundance") %>%
  mutate(censusdate = as.Date(censusdate))

ggplot(corerats, aes(censusdate, abundance)) +
  geom_line() +
  facet_wrap(vars(species), scales = "free")

ggplot(filter(corerats, censusdate > as.Date("2005-01-01"), species != "DS"), aes(censusdate, abundance, color = species)) +
  geom_line() 
  facet_wrap(vars(species), scales = "free")


```

```{r}
inds <- portalr::summarise_individual_rodents(type = "Rodents", time = "censusdate") 

inds <- inds %>%
  filter(!is.na(wgt)) %>%
  filter(species %in% c("DM", "DO", "DS", "PP", "PB"))

ggplot(inds, aes(log(wgt), color = species, group = species, fill = species)) +
  geom_density(alpha = .2)

```
