---
title: "Covariates of rodent community change"
output: #word_document
   github_document:
        df_print: kable
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))
library(soar)
library(ggplot2)
library(dplyr)
library(mgcv)
library(gratia)
library(multipanelfigure)

theme_set(theme_bw())

treatl <- get_treatment_means() %>%
  remove_switch()

era_df <- make_era_df() %>%
  mutate(year = format.Date(event_date, "%Y")) %>%
  mutate(year = as.integer(year))

ndvi_scale <-   scale_color_viridis_d(option = "mako", end = .8) 


```

# Total rodent abundance

```{r}

te_anomaly <- treatl %>%
  filter(oplottype == "CC") %>%
  mutate(te_mean = mean(total_e)) %>%
  mutate(te_anomaly = total_e - te_mean) %>%
  mutate(te_anomaly_positive = te_anomaly > 0)
te_plot <- ggplot(te_anomaly, aes(censusdate, total_e)) +
  geom_line() +
  ylab(bquote(Etot[C])) +
  xlab("Date") +
  ggtitle("Total rodent energy use") +
  scale_x_date(sec.axis = dup_axis(name = NULL, breaks = era_df$event_date, labels = era_df$event_name)) + 
  theme(axis.title.y = element_text(size =  10), legend.title = element_blank(), legend.text = element_text(size =  10))+ 
  theme( title = element_text(size = 10), axis.text = element_text(size = 10), legend.background = element_blank(), legend.direction = "vertical", legend.position = "none") + geom_segment(data = era_df, aes(x = event_date, xend = event_date, y = 0, yend = 1800), linetype = 3, inherit.aes = F) +
  geom_hline(yintercept = te_anomaly$te_mean[1], linetype = 2) +
  geom_text(data = data.frame(), aes(as.Date("1990-10-01"), 750, label = "Long-term mean"))
te_plot

te_anom_plot <- ggplot(te_anomaly, aes(censusdate, te_anomaly, color = te_anomaly_positive, fill = te_anomaly_positive)) +
  geom_col() +
  ylab("Difference from \nlong-term mean") +
  xlab("Date") +
  ggtitle("Total rodent energy use anomaly") +
 geom_segment(data = era_df, aes(x = event_date, xend = event_date, y = -550, yend = 1250), linetype = 3, inherit.aes = F) +
  scale_x_date(sec.axis = dup_axis(name = NULL, breaks = era_df$event_date, labels = era_df$event_name)) +
  theme(axis.title.y = element_text(size =  10), legend.title = element_blank(), legend.text = element_text(size =  10))+ theme( title = element_text(size = 10), axis.text = element_text(size = 10), legend.background = element_blank(), legend.direction = "vertical", legend.position = "none") + scale_color_viridis_d(option = "cividis", begin= .1, end =.8)

te_anom_plot
```

# NDVI

```{r}



era_labs <- scale_x_date(sec.axis = dup_axis(name = NULL, breaks = era_df$event_date, labels = era_df$event_name)) 
era_lines <-   geom_vline(xintercept = era_df$event_date, linetype = 3)


era_labs_year <- scale_x_continuous(sec.axis = dup_axis(name = NULL, breaks = era_df$year, labels = era_df$event_name)) 
era_lines_year <-   geom_vline(xintercept = era_df$year, linetype = 3)


ndvi_dat <- portalr::ndvi()


ndvi_dat <- ndvi_dat %>%
  mutate(month = format.Date(date, "%m"),
         year = format.Date(date, "%Y")) %>%
  filter(date > as.Date("1988-01-01"), date < as.Date("2020-02-01")) %>%
  group_by(month) %>%
  mutate(ndvi_norm = mean(ndvi)) %>%
  ungroup() %>%
  mutate(ndvi_difference = ndvi - ndvi_norm,
         ndvi_prop = ndvi / ndvi_norm) %>%
  mutate(numdate = as.numeric(date)) 


ndvi_plot <- ggplot(ndvi_dat, aes(date, ndvi_difference, color = ndvi_difference > 0)) +
  geom_col() +
  ndvi_scale +
  era_labs+ 
  era_lines+
  theme(legend.position = "none", axis.text = element_text(size = 10)) +
  xlab("Date") +
  ylab("Difference from \nlong-term mean") +
  ggtitle("NDVI anomaly")
ndvi_plot
```

# Drought (SPEI index)

```{r}
library(SPEI)

weather <- portalr::weather(level = "monthly", fill = T)

weather <- weather %>%
    dplyr::mutate(date = format(lubridate::parse_date_time(paste(month, year, sep=" "),
                                                           orders = c("m/Y")), "%m-%Y")) %>%
    dplyr::mutate(date = as.Date(paste("01",date,sep="-"), format="%d-%m-%Y"))  %>%
  mutate(numdate = as.numeric(date)) %>%
  dplyr::filter(date < "2020-02-01")


weather_full <- expand.grid(year = c(min(weather$year) : max(weather$year)),
  month = c(1:12)
) %>%
  left_join(mutate(weather, month = as.numeric(month), year = as.numeric(year))) %>%
  mutate(datestr = paste0(year, "-01-", month)) %>%
  mutate(newdate = as.Date(datestr, format = "%Y-%d-%m")) %>%
  arrange(newdate)

precip_ts <- ts(weather_full$precipitation, start = weather_full$newdate[1], frequency = 12)

precip_ts_interp <- imputeTS::na_interpolation(precip_ts)

meant_ts <- ts(weather_full$meantemp, start = weather_full$newdate[1], frequency = 12)

meant_ts_interp <- imputeTS::na_interpolation(meant_ts)

weather_full_drought <- weather_full %>%
  mutate(precip_interp = precip_ts_interp,
         temp_interp = meant_ts_interp) %>% 
  filter(year > 1988, year < 2021) %>%
  mutate(thorn = SPEI::thornthwaite(temp_interp, lat = 31.938908)) %>%
  mutate(cbal = precip_interp - thorn) %>%
  mutate(spei1 = spei(cbal, 1)$fitted, 
spei6 = spei(cbal, 6)$fitted, 
         spei12 = as.numeric(spei(cbal, 12)$fitted),
         spei18 = spei(cbal, 18)$fitted) %>%
  mutate(oera = as.ordered(ifelse(year < 1996, "a", ifelse(year < 2010, "b", "c")))) %>%
  left_join(era_df)  %>%
  mutate(dry = as.numeric(spei12) < 0)


space_label <- function(lab) {
  return(paste0(lab, "  "))
}

spei_plot <- ggplot(weather_full_drought, aes(newdate, spei12, color = dry, fill = dry)) + 
  geom_col() + 
  scale_color_viridis_d(option = "turbo", begin = .1, end = .8) +  
  scale_fill_viridis_d(option = "turbo", begin = .1, end = .8) +
  theme(legend.position = "none", axis.text = element_text(size = 10)) +
  geom_segment(data = era_df, aes(x = event_date, xend = event_date, y = -2.2, yend = 2.2), linetype = 3, inherit.aes = F) +
  scale_x_date(sec.axis = dup_axis(name = NULL, breaks = era_df$event_date, labels = era_df$event_name), limits = c(as.Date("1988-01-01"), as.Date("2020-01-01"))) +
  xlab("Date") +
  ylab("12-month SPEI index\n") +
  geom_hline(yintercept = 1, color = "blue", alpha = .3) +
  geom_hline(yintercept = -1, color ="red", alpha = .3) +
  ggtitle("Drought (SPEI index)") +
  scale_y_continuous(n.breaks = 5, labels = space_label )

spei_plot

```

# All plots

```{r, fig.dim = c(6,8)}
library(multipanelfigure)

all_panels <- multi_panel_figure(columns = 1, rows =3, row_spacing = c(5, 0, 0)) %>%
  fill_panel(te_anom_plot) %>%
  fill_panel(ndvi_plot) %>%
  fill_panel(spei_plot) 

all_panels
```