---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}


library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(F, T, F, T) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = as.factor(plot_type))

treatment_means <- get_rodent_data(F, F, F, T) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = as.factor(plot_type)) 

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()


```

```{r}

treatment_annuals <- treatment_means %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot_type, era, nplots) %>%
  summarize(total_e = mean(total_e),
            dipo_e = mean(dipo_e),
            smgran_e = mean(smgran_e),
            pb_e = mean(pb_e),
            pp_e = mean(pp_e),
            tinygran_e = mean(tinygran_e),
            nsamples = dplyr::n(),
            nperiods = length(unique(period))) %>%
  ungroup()

```

```{r}


ggplot(treatment_annuals, aes(censusyear, total_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8) +
  ggtitle("Total E annual means by treatment") +
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


ggplot(treatment_annuals, aes(censusyear, smgran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8) +
  ggtitle("Small granivore E annual means by treatment")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")



ggplot(treatment_annuals, aes(censusyear, tinygran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8) +
  ggtitle("Tiny gran E annual means by treatment")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


```

```{r}
sg_e_mod <- gam(smgran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

sg_e_pdat <- treatment_means %>%
  select(period, oplottype, era) %>%
  mutate(type = "smgran") %>%
  distinct()

sg_e_pred <- get_predicted_vals(sg_e_mod, sg_e_pdat)


sg_rawe_ce_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
sg_rawe_ce_cc_pred <- add_exclosure_diff(sg_e_pred, sg_rawe_ce_cc_diff)
plot_fitted_pred(filter(sg_rawe_ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + 
  ggtitle("GAM diff smgran raw energy CC v CE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")

```


```{r}
tg_e_mod <- gam(tinygran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

tg_e_pdat <- treatment_means %>%
  select(period, oplottype, era) %>%
  mutate(type = "tinygran") %>%
  distinct()

tg_e_pred <- get_predicted_vals(tg_e_mod, tg_e_pdat)

tg_rawe_ee_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
tg_rawe_ee_cc_pred <- add_exclosure_diff(tg_e_pred, tg_rawe_ee_cc_diff)
plot_fitted_pred(filter(tg_rawe_ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype") +
  ggtitle("GAM diff tgran raw e CC v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


```


```{r}
total_e_mod <- gam(total_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

total_e_pdat <- treatment_means %>%
  select(period, oplottype, era) %>%
  mutate(type = "all_energy") %>%
  distinct()

total_e_pred <- get_predicted_vals(total_e_mod, total_e_pdat)

plot_fitted_pred(total_e_pred, comparison_variable = "oplottype") +
  ggtitle("GAM fit total raw e by treatment")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


total_rawe_ee_cc_diff <- get_exclosure_diff(total_e_mod, total_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
total_rawe_ee_cc_pred <- add_exclosure_diff(total_e_pred, total_rawe_ee_cc_diff)
plot_fitted_pred(filter(total_rawe_ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype") +
  ggtitle("GAM diff total raw e CC v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")

```

## Ratios


```{r}
treatment_ratios <- get_total_energy_ratios(treatment_means) %>%
  mutate(sg_of_c = smgran_e / total_e_c,
         tg_of_c = tinygran_e / total_e_c) %>%
  mutate(total_e_of_c = 0.0000000001 + total_e_of_c,
         sg_of_c = 0.0000000001 + sg_of_c,
         tg_of_c = 0.0000000001 + tg_of_c) %>%
  mutate(plot_type = ifelse(plot_type == "CC", "C", plot_type)) %>%
  mutate(fplottype = factor(plot_type))

treatment_ratios_annual <- treatment_ratios %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, era, fplottype) %>%
  summarize(mean_total_ratio = mean(total_e_of_c),
         mean_sg_ratio = mean(sg_of_c),
         mean_tg_ratio = mean(tg_of_c),
         nperiods = length(unique(period)),
         nsamples = dplyr::n()) %>%
  ungroup()

```


```{r}

sg_ratio_gam <- gam(sg_of_c ~ fplottype + s(period, k = 100) + s(period, by = fplottype, k = 100), family = "Gamma", data = treatment_ratios)

sg_ratio_pdat <- select(treatment_ratios, era, fplottype, period) %>%
  mutate(type = "sgmran") %>%
  distinct()

sg_ratio_pred <- get_predicted_vals(sg_ratio_gam, sg_ratio_pdat)

sg_ratio_ee_cc_diff <- get_exclosure_diff(sg_ratio_gam, sg_ratio_pred, comparison_variable = "fplottype", comparison_level = 2)

sg_ratio_ee_cc_pred <- add_exclosure_diff(sg_ratio_pred, sg_ratio_ee_cc_diff)

plot_fitted_pred(filter(sg_ratio_ee_cc_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  ggtitle("GAM diff smgran ratio EE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")




```


```{r}

tg_ratio_gam <- gam(tg_of_c ~ fplottype + s(period, k = 100) + s(period, by = fplottype, k =100), family = "Gamma", data = treatment_ratios)

tg_ratio_pdat <- select(treatment_ratios, era, fplottype, period) %>%
  mutate(type = "tinygran") %>%
  distinct()

tg_ratio_pred <- get_predicted_vals(tg_ratio_gam, tg_ratio_pdat)

tg_ratio_ee_cc_diff <- get_exclosure_diff(tg_ratio_gam, tg_ratio_pred, comparison_variable = "fplottype", comparison_level = 2)

tg_ratio_ee_cc_pred <- add_exclosure_diff(tg_ratio_pred, tg_ratio_ee_cc_diff)

plot_fitted_pred(filter(tg_ratio_ee_cc_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  ggtitle("GAM diff tgran ratio EE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


```

```{r}

total_ratio_gam <- gam(total_e_of_c ~  s(period, k = 100), family = "Gamma", data = filter(treatment_ratios, fplottype != "C"))

total_ratio_pdat <- select(treatment_ratios, era, 
                          fplottype, period) %>%
  mutate(type = "all_energy") %>%
  filter(fplottype != "C")

total_e_ratio_pred <- get_predicted_vals(total_ratio_gam, total_ratio_pdat)

plot_fitted_pred(filter(total_e_ratio_pred), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_color_viridis_d(begin = .4, end = .8) +
  scale_fill_viridis_d(begin = .4, end = .8) +
  ggtitle("Total energy ratio fits + diff, CE v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")

```

## By era

##### Era means:

```{r}

era_means <- treatment_means %>%
  group_by(era, plot_type) %>%
  mutate(total_e_mean = mean(total_e),
         smgran_e_mean = mean(smgran_e),
         tinygran_e_mean = mean(tinygran_e)) %>%
  ungroup()
# 
# ggplot(era_means, aes(period, total_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, total_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 
# 
# ggplot(era_means, aes(period, smgran_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, smgran_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 
# 
# 
# ggplot(era_means, aes(period, tinygran_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, tinygran_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)

select(era_means, era, oplottype, total_e_mean, smgran_e_mean, tinygran_e_mean) %>%
  distinct()



```

### gls on actual vals

##### Total energy raw GLS

```{r}

library(nlme)
library(lsmeans)

te_gls <- gls(total_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
summary(pairs(lsmeans(te_gls, specs = ~oplottype | era)))
```

##### Small gran raw GLS

```{r}
sg_gls <- gls(smgran_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
summary(pairs(lsmeans(sg_gls, specs = ~oplottype | era)))
```

##### Tiny gran raw GLS

```{r}

tg_gls <- gls(tinygran_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
summary(pairs(lsmeans(tg_gls, specs = ~oplottype | era)))


```

### gls on ratios

##### Era ratios:

```{r}

era_ratios <- treatment_ratios %>%
  group_by(era, oplottype) %>%
  mutate(te_mean = mean(total_e_of_c),
         sg_mean = mean(sg_of_c),
         tg_mean = mean(tg_of_c)) %>%
  ungroup()


select(era_ratios, era, oplottype, te_mean, sg_mean, tg_mean) %>%
  distinct()

ggplot(era_ratios, aes(period, te_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, total_e_of_c), alpha = .3) +
  scale_color_viridis_d(end = .8)


# ggplot(era_ratios, aes(period, sg_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, sg_of_c), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 
# 
# 
# ggplot(era_ratios, aes(period, tg_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, tg_of_c), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 

treatment_ratios_no_c <- filter(treatment_ratios, fplottype != "C") %>%
  mutate(fplottype = as.factor(plot_type))
```

##### Total energy ratios GLS

This fit includes CC plots, for which ratio always = 1. 

```{r}
ter_gls <- gls(total_e_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype))
summary(pairs(lsmeans(ter_gls, specs = ~fplottype | era)))

```


##### Smgran ratio GLS

```{r}
sgr_gls <- gls(sg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype))
summary(pairs(lsmeans(sgr_gls, specs = ~fplottype | era)))

```

##### Tiny gran ratio GLS

```{r}
tgr_gls <- gls(tg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype))
summary(pairs(lsmeans(tgr_gls, specs = ~fplottype | era)))

```



### glm on ratios

##### Total energy GLM

With  controls:

```{r}

ter_glm <- gam(total_e_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma")
summary(pairs(regrid(lsmeans(ter_glm, specs = ~fplottype | era))))
```

##### Small granivore ratio GLM

```{r}
sgr_glm <- gam(sg_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma")
#summary(pairs(lsmeans(sgr_glm, specs = ~fplottype | era)))
summary(pairs(regrid(lsmeans(sgr_glm, specs = ~fplottype | era))))
```


##### Tiny granivore ratio GLM

```{r}
tgr_glm <- gam(tg_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma")
summary(pairs(regrid(lsmeans(tgr_glm, specs = ~fplottype | era))))

```