---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>%
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()

treatment_means <- get_rodent_data(use_christensen_plots, F, F) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

# treatment_ratios <- get_total_energy_ratios(treatment_means)

```

```{r}

treatment_annuals <- treatment_means %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot_type, era, nplots) %>%
  summarize(total_e = mean(total_e),
            dipo_e = mean(dipo_e),
            smgran_e = mean(smgran_e),
            pb_e = mean(pb_e),
            pp_e = mean(pp_e),
            tinygran_e = mean(tinygran_e),
            nsamples = dplyr::n(),
            nperiods = length(unique(period))) %>%
  ungroup()

```

```{r}


ggplot(treatment_annuals, aes(censusyear, total_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)


ggplot(treatment_annuals, aes(censusyear, smgran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)


ggplot(treatment_annuals, aes(censusyear, tinygran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)

```

```{r}
sg_e_mod <- gam(smgran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

sg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "smgran")

sg_e_pred <- get_predicted_vals(sg_e_mod, sg_e_pdat)

plot_fitted_pred(sg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(sg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(sg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(sg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```


```{r}
tg_e_mod <- gam(tinygran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

tg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "tinygran")

tg_e_pred <- get_predicted_vals(tg_e_mod, tg_e_pdat)

plot_fitted_pred(tg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(tg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(tg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(tg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```


#### Combine CE and CE thru 2015

This does not make a material difference. Scoots convergence of C and E for smgran up a few periods, and otherwise everything is the same. 

```{r}

treatment_means <- get_rodent_data(use_christensen_plots, F, F) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type)) %>%
  filter(period < 430)


treatment_means_to_2015 <- treatment_means %>% 
  filter(period < 430) %>%
  mutate(orig_plot_type = substr(plot_type, 1,1)) %>%
  mutate(oorig_plot_type = ordered(orig_plot_type))
```

##### With all 3 types - you need these so you look at the same time interval

```{r}
sg_e_mod <- gam(smgran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

sg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "smgran")

sg_e_pred <- get_predicted_vals(sg_e_mod, sg_e_pdat)

plot_fitted_pred(sg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(sg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(sg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(sg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```


```{r}
tg_e_mod <- gam(tinygran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

tg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "tinygran")

tg_e_pred <- get_predicted_vals(tg_e_mod, tg_e_pdat)

plot_fitted_pred(tg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(tg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(tg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(tg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```

##### Combined CE and CC, because they're both C thru 2015
```{r}
sg_e_mod <- gam(smgran_e ~ oorig_plot_type + s(period, k = 20) + s(period, by = oorig_plot_type, k = 20), family = "tw", data = treatment_means_to_2015)

sg_e_pdat <- treatment_means_to_2015 %>%
  select(period, oorig_plot_type) %>%
  mutate(type = "smgran") %>%
  distinct()

sg_e_pred <- get_predicted_vals(sg_e_mod, sg_e_pdat)

plot_fitted_pred(sg_e_pred, comparison_variable = "oorig_plot_type")

ee_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oorig_plot_type", reference_level = 1, comparison_level = 2)
ee_cc_pred <- add_exclosure_diff(sg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oorig_plot_type != "CE"), comparison_variable = "oorig_plot_type")

```


```{r}
tg_e_mod <- gam(tinygran_e ~ oorig_plot_type + s(period, k = 20) + s(period, by = oorig_plot_type, k = 20), family = "tw", data = treatment_means_to_2015)

tg_e_pdat <- treatment_means_to_2015 %>%
  select(period, oorig_plot_type) %>%
  mutate(type = "tinygran") %>%
  distinct()

tg_e_pred <- get_predicted_vals(tg_e_mod, tg_e_pdat)

plot_fitted_pred(tg_e_pred, comparison_variable = "oorig_plot_type")

ee_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oorig_plot_type", reference_level = 1, comparison_level = 2)
ee_cc_pred <- add_exclosure_diff(tg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oorig_plot_type != "CE"), comparison_variable = "oorig_plot_type")

```