---
title: "Christensen plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(mgcv)
library(ggplot2)
library(cowplot)

rats <- read.csv(here::here("lore", "2020_redux", "christensen_plots.csv"))

energy <- rats %>%
  select(censusdate, plot, treatment, energy) %>%
  group_by(censusdate, plot, treatment) %>%
  summarize(n = dplyr::n(),
            e = sum(energy, na.rm = T))  %>%
  ungroup() %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(numericdate = as.numeric(censusdate) / 1000) %>%
  select(-n) %>%
  rename(n = e) %>%
  select(plot, censusdate, numericdate, treatment, n) %>%
  filter(censusdate > "2013-03-11")


source(here::here("lore", "2019_switch", "FinalAnalysis", 'analysis_functions.R'))
theme_set(theme_bw())
#cbPalette <- c( "#e19c02","#999999", "#56B4E9", "#0072B2", "#D55E00", "#F0E442", "#009E73", "#CC79A7")
cbbPalette <- c("#000000", "#009E73", "#e79f00", "#9ad0f3", "#0072B2", "#D55E00", 
                "#CC79A7", "#F0E442")
```

```{r}


energy <- mutate(energy,
                 oTreatment = ordered(treatment, levels = c('CC','EC','XC')),
                 oPlot      = ordered(plot),
                 plot       = factor(plot))

# GAM model -- includes plot smooths
energy.gam <- gam(n ~ oPlot + oTreatment + s(numericdate, k = 20) +
                    s(numericdate, by = oTreatment, k = 15) +
                    s(numericdate, by = oPlot),
                  data = energy, method = 'REML', family = tw, select = TRUE)

# plot treatment effects (exclude plot smooths)
exVars.energy <- c('oPlot', paste0('s(numericdate):oPlot', c(5,6,7,11,13,14,17,18,24)))

treatPred.energy <- predict_treat_effect(energy, np = 500, MODEL=energy.gam, exVars.energy)

energy.plt <- plot_gam_prediction(treatPred.energy, energy, Palette = cbbPalette[c(6,1,4)], ylab='Metabolic Flux \n(kJ)')
energy.plt
#ggsave('energy-treatment-effects.png', energy.plt,width=6,height=2.5)

# difference of smooths
d1 <- osmooth_diff(energy.gam, treatPred.energy, "numericdate", "CC", "EC", var = "oTreatment", removePara = FALSE)
d2 <- osmooth_diff(energy.gam, treatPred.energy, "numericdate", "CC", "XC", var = "oTreatment", removePara = FALSE)
diffs.energy <- rbind(d1,d2)
energy.diffPlt <- plot_smooth_diff(diffs.energy,Palette=cbbPalette[c(1,4)])
energy.diffPlt
#ggsave('energy-difference.png', energy.diffPlt,width=6,height=2.5)

## Cowplot grid
energy_plot = plot_grid(energy.plt, energy.diffPlt, labels = "AUTO", ncol = 1, align = 'v')
energy_plot
#ggsave('Figures/energy-gam
```