---
title: "SPEI drought index"
output: github_document
---

```{r setup, include=FALSE}
library(portalr)
library(dplyr)
library(ggplot2)
library(soar)
library(SPEI)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))

era_grid <-   facet_grid(cols = vars(oera), space = "free", scales = "free_x")
```

```{r}

weather <- weather(level = "monthly", fill = T)

weather <- weather %>%
    dplyr::mutate(date = format(lubridate::parse_date_time(paste(month, year, sep=" "),
                                                           orders = c("m/Y")), "%m-%Y")) %>%
    dplyr::mutate(date = as.Date(paste("01",date,sep="-"), format="%d-%m-%Y"))  %>%
  mutate(numdate = as.numeric(date))


weather_full <- expand.grid(year = c(min(weather$year) : max(weather$year)),
  month = c(1:12)
) %>%
  left_join(mutate(weather, month = as.numeric(month), year = as.numeric(year))) %>%
  mutate(datestr = paste0(year, "-01-", month)) %>%
  mutate(newdate = as.Date(datestr, format = "%Y-%d-%m")) %>%
  arrange(newdate)
```


## Summary

The period since 2010 has had two periods of long and severe drought, longer and more severe than previous successive droughts, interspersed with a relatively wet wet period (compared to the 2000s). However, there have been several droughts - including a single long, severe drought in the early 2000s - that did not coincide with major shifts in the rodents.

```{r}

precip_ts <- ts(weather_full$precipitation, start = weather_full$newdate[1], frequency = 12)

precip_ts_interp <- imputeTS::na_interpolation(precip_ts)

meant_ts <- ts(weather_full$meantemp, start = weather_full$newdate[1], frequency = 12)

meant_ts_interp <- imputeTS::na_interpolation(meant_ts)

weather_full_drought <- weather_full %>%
  mutate(precip_interp = precip_ts_interp,
         temp_interp = meant_ts_interp) %>% 
  filter(year > 1988, year < 2021) %>%
  mutate(thorn = SPEI::thornthwaite(temp_interp, lat = 31.938908)) %>%
  mutate(cbal = precip_interp - thorn) %>%
  mutate(spei1 = spei(cbal, 1)$fitted, 
spei6 = spei(cbal, 6)$fitted, 
         spei12 = spei(cbal, 12)$fitted,
         spei18 = spei(cbal, 18)$fitted) %>%
  mutate(oera = as.ordered(ifelse(year < 1996, "a", ifelse(year < 2010, "b", "c"))))


write.csv(weather_full_drought, "spei.csv")

 ggplot(weather_full_drought, aes(date, spei6, color = spei6 > 0)) + geom_col() + scale_color_viridis_d(option = "turbo", begin = .1, end = .8, direction = -1) + era_grid + theme(legend.position = "none") + ggtitle("SPEI 6-month drought index")
ggplot(weather_full_drought, aes(date, spei12, color = spei12 > 0)) + geom_col() + scale_color_viridis_d(option = "turbo", begin = .1, end = .8, direction = -1)+ era_grid + theme(legend.position = "none") + ggtitle("SPEI 12-month drought index")
ggplot(weather_full_drought, aes(date, spei18, color = spei18 > 0)) + geom_col() + scale_color_viridis_d(option = "turbo", begin = .1, end = .8, direction = -1)+ era_grid + theme(legend.position = "none") + ggtitle("SPEI 18-month drought index")


```


