---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>%
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()

treatment_means <- get_rodent_data(use_christensen_plots, F, F) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = as.factor(plot_type))

# treatment_ratios <- get_total_energy_ratios(treatment_means)

```


## Ratios


```{r}
treatment_ratios <- get_total_energy_ratios(treatment_means) 

control_means <- filter(treatment_ratios, plot_type == "CC") %>%
  select(period, censusdate, total_e_c)

plot_ratio_totals <- plot_totals %>%
  left_join(control_means) %>%
  mutate(total_e_of_c = total_e / total_e_c,
    sg_of_c = smgran_e / total_e_c,
         tg_of_c = tinygran_e / total_e_c) %>%
  mutate(total_e_of_c = 0.0000000001 + total_e_of_c,
         sg_of_c = 0.0000000001 + sg_of_c,
         tg_of_c = 0.0000000001 + tg_of_c) %>%
  mutate(fplottype = factor(plot_type)) %>%
  mutate(sg_int = ceiling(smgran_e),
         tgran_int = ceiling(tinygran_e),
         totale_int = ceiling(total_e))

```

```{r}

ggplot(plot_ratio_totals, aes(censusdate, sg_of_c, color = fplottype, group = plot)) +
  geom_line()

```

```{r}
smgran_glm <- glm(sg_int ~ oplottype * era, data = plot_ratio_totals, family= poisson)

#smgran_glm <- glm(smgran_e ~ oplottype * era, data = plot_ratio_totals, family= tweedie())


library(emmeans)

pairs(emmeans(smgran_glm, ~ oplottype | era))

plot(pairs(emmeans(smgran_glm, ~ oplottype | era)))

plot(regrid(emmeans(smgran_glm, ~ oplottype | era)))

regrid(emmeans(smgran_glm, ~ oplottype | era))

library(lme4)
smgran_glmer <- glmer(sg_int ~ oplottype * era + (1 |plot), data = plot_ratio_totals, family= poisson)

pairs(emmeans(smgran_glmer, ~ oplottype | era))

regrid(emmeans(smgran_glmer, ~ oplottype | era))


plot(regrid(emmeans(smgran_glmer, ~ oplottype | era)))

plot(pairs(emmeans(smgran_glmer, ~ oplottype | era)))


smgran_ratio_glmer <- glmer(sg_of_c ~ oplottype * era + (1 | plot), data = plot_ratio_totals, family = Gamma)


pairs(emmeans(smgran_ratio_glmer, ~ oplottype | era))

regrid(emmeans(smgran_ratio_glmer, ~ oplottype | era))


plot(regrid(emmeans(smgran_ratio_glmer, ~ oplottype | era)))

plot(pairs(emmeans(smgran_ratio_glmer, ~ oplottype | era)))


smgran_glm_pred <- predict(smgran_glm, type = "link", se.fit = T)

smgran_ilink <- smgran_glm$family$linkinv

smgran_glm_pred_vals <- data.frame(resp = smgran_ilink(smgran_glm_pred$fit),
                                   lower = smgran_ilink(smgran_glm_pred$fit) - smgran_ilink(2 * smgran_glm_pred$se.fit),
                                   upper = smgran_ilink(smgran_glm_pred$fit) + smgran_ilink(2 * smgran_glm_pred$se.fit) ) %>%
  cbind(plot_ratio_totals)

ggplot(smgran_glm_pred_vals, aes(oplottype, resp)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper)) +
  facet_wrap(vars(era))
```

Weirdly the GLM has NO ERROR AT ALL. I don't trust that!. The GLMER does, but it's trickier to get SEs out of a GLMMER.


```{r}

library(nlme)

smgran_lme <- lme(smgran_e ~ oplottype * era, random= ~1 | plot, data =plot_ratio_totals )

qqnorm(smgran_lme)

plot((emmeans(smgran_lme, ~ oplottype | era)))

plot(pairs(emmeans(smgran_lme, ~ oplottype | era)))
```

The LME is predicting negative values. 


```{r}

smgran_gls <- gls(smgran_e ~ oplottype * era,  data =plot_ratio_totals )

qqnorm(smgran_gls)
plot((emmeans(smgran_gls, ~ oplottype | era)))

plot(pairs(emmeans(smgran_gls, ~ oplottype | era)))

```


GLS doesn't, for whatever reason.



```{r}
tgran_glmer <- glmer(tgran_int ~ oplottype * era + (1 |plot), data = plot_ratio_totals, family= poisson)

pairs(emmeans(tgran_glmer, ~ oplottype | era))

plot((emmeans(tgran_glmer, ~ oplottype | era)))

plot(pairs(emmeans(tgran_glmer, ~ oplottype | era)))



tgran_glm <- glm(tgran_int ~ oplottype * era, data = plot_ratio_totals, family= quasipoisson)

pairs(emmeans(tgran_glm, ~ oplottype | era))

plot((emmeans(tgran_glm, ~ oplottype | era)))

plot(pairs(emmeans(tgran_glm, ~ oplottype | era)))


tgran_glm_pred <- predict(tgran_glm, type = "link", se.fit = T)

tgran_ilink <- tgran_glm$family$linkinv

tgran_glm_pred_vals <- data.frame(resp = tgran_ilink(tgran_glm_pred$fit),
                                   lower = tgran_ilink(tgran_glm_pred$fit) - tgran_ilink(2 * tgran_glm_pred$se.fit),
                                   upper = tgran_ilink(tgran_glm_pred$fit) + tgran_ilink(2 * tgran_glm_pred$se.fit) ) %>%
  cbind(plot_ratio_totals)

ggplot(tgran_glm_pred_vals, aes(oplottype, resp)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper)) +
  facet_wrap(vars(era)) 


ggplot(tgran_glm_pred_vals, aes(oplottype, tinygran_e)) +
  geom_boxplot() +
  facet_wrap(vars(era)) +
  geom_point(aes(y = resp), color = "red") +
    geom_errorbar(aes(ymin = lower, ymax = upper), color = "red") 



tgran_ratio_glmer <- glmer(tg_of_c ~ oplottype * era + (1 | plot), data = plot_ratio_totals, family = Gamma)


pairs(emmeans(tgran_ratio_glmer, ~ oplottype | era))

regrid(emmeans(tgran_ratio_glmer, ~ oplottype | era))


plot(regrid(emmeans(tgran_ratio_glmer, ~ oplottype | era)))

plot(pairs(emmeans(tgran_ratio_glmer, ~ oplottype | era)))


```


