---
title: "(P)(C)CA on annual plants"
output: 
    github_document:
       df_print: kable
       toc: true
---
```{r setup, include=FALSE}
library(dplyr)
library(soar)
library(ggplot2)
library(vegan)

knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))

theme_set(theme_bw())

winter_treat_abunds <- get_treatment_abundance_matrix()
summer_treat_abunds <- get_treatment_abundance_matrix("summer")

winter_plot_abunds <- get_plot_abundance_matrix()
summer_plot_abunds <- get_plot_abundance_matrix("summer")


```

# Winter

## CA

### Plot level

```{r}

winter_plot_abund_matrix <- winter_plot_abunds %>%
  ungroup() %>%
  filter(plot_total_abundance >0 ) %>%
  select(-c(year, plot, season, combined_trt, empty_plot, quadrats_censused, plot_total_abundance)) %>%
  mutate_all(sqrt)


winter_plot_ca <- cca(winter_plot_abund_matrix)

barplot(winter_plot_ca$CA$eig / winter_plot_ca$tot.chi, names.arg = 1:winter_plot_ca$CA$rank, cex.names = 0.5)

(winter_plot_ca$CA$eig / winter_plot_ca$tot.chi)[1:5]


preds <-  winter_plot_abunds %>%
  ungroup() %>%
  filter(plot_total_abundance > 0) %>%
  select((c(plot, year, combined_trt)))%>%
  mutate(rod_era = as.ordered(ifelse(year < 1997, "a",
                                     ifelse(year < 2010, "b",
                                            "c"))))

winter_plot_ca_scores <- as.data.frame(scores(winter_plot_ca, display = "sites", scaling = "sites")) %>%
  cbind(preds)

ggplot(winter_plot_ca_scores, aes(CA1, CA2, color = rod_era)) + 
  geom_point()  +
  stat_ellipse() +
    ylim(-2.5, 1) +
  facet_wrap(vars(combined_trt))
```

### Treatment level

```{r}

plantcols <- colnames(winter_treat_abunds)[7:ncol(winter_treat_abunds)]

stdize <- function(plantcol, totalcol) {
  return(5 * (plantcol / totalcol))
}

winter_treat_abund_matrix <- winter_treat_abunds 
winter_treat_abund_matrix[,plantcols] <- apply(winter_treat_abund_matrix[, plantcols], MARGIN =2, FUN = stdize, totalcol = winter_treat_abund_matrix[,"total_plots"])
colnames(winter_treat_abund_matrix)[7:ncol(winter_treat_abund_matrix)] <- plantcols

winter_treat_abund_matrix <- winter_treat_abund_matrix %>%
  ungroup() %>%
  filter(total_abundance >0 ) %>%
  select(-c(year, season, combined_trt, total_plots, total_empty_plots, total_abundance)) %>%
  mutate_all(sqrt)



winter_treat_ca <- cca(winter_treat_abund_matrix)

barplot(winter_treat_ca$CA$eig / winter_treat_ca$tot.chi, names.arg = 1:winter_treat_ca$CA$rank, cex.names = 0.5)

(winter_treat_ca$CA$eig / winter_treat_ca$tot.chi)[1:5]


preds <-  winter_treat_abunds %>%
  ungroup() %>%
  filter(total_abundance > 0) %>%
  select((c(year, combined_trt)))%>%
  mutate(rod_era = as.ordered(ifelse(year < 1997, "a",
                                     ifelse(year < 2010, "b",
                                            "c"))))

winter_treat_ca_scores <- as.data.frame(scores(winter_treat_ca, display = "sites", scaling = "sites")) %>%
  cbind(preds)

ggplot(winter_treat_ca_scores, aes(CA1, CA2, color = rod_era)) + 
  geom_point()  +
  stat_ellipse() +
  facet_wrap(vars(combined_trt))
```


# Summer

## CA

### Plot level

```{r}

summer_plot_abund_matrix <- summer_plot_abunds %>%
  ungroup() %>%
  filter(plot_total_abundance >0 ) %>%
  select(-c(year, plot, season, combined_trt, empty_plot, quadrats_censused, plot_total_abundance)) %>%
  mutate_all(sqrt)


summer_plot_ca <- cca(summer_plot_abund_matrix)

barplot(summer_plot_ca$CA$eig / summer_plot_ca$tot.chi, names.arg = 1:summer_plot_ca$CA$rank, cex.names = 0.5)

(summer_plot_ca$CA$eig / summer_plot_ca$tot.chi)[1:5]


preds <-  summer_plot_abunds %>%
  ungroup() %>%
  filter(plot_total_abundance > 0) %>%
  select((c(plot, year, combined_trt)))%>%
  mutate(rod_era = as.ordered(ifelse(year < 1997, "a",
                                     ifelse(year < 2010, "b",
                                            "c"))))

summer_plot_ca_scores <- as.data.frame(scores(summer_plot_ca, display = "sites", scaling = "sites")) %>%
  cbind(preds)

ggplot(summer_plot_ca_scores, aes(CA1, CA2, color = rod_era)) + 
  geom_point()  +
  stat_ellipse() +
    ylim(-2.5, 1) +
  facet_wrap(vars(combined_trt))
```

### Treatment level

```{r}

plantcols <- colnames(summer_treat_abunds)[7:ncol(summer_treat_abunds)]

stdize <- function(plantcol, totalcol) {
  return(5 * (plantcol / totalcol))
}

summer_treat_abund_matrix <- summer_treat_abunds 
summer_treat_abund_matrix[,plantcols] <- apply(summer_treat_abund_matrix[, plantcols], MARGIN =2, FUN = stdize, totalcol = summer_treat_abund_matrix[,"total_plots"])
colnames(summer_treat_abund_matrix)[7:ncol(summer_treat_abund_matrix)] <- plantcols

summer_treat_abund_matrix <- summer_treat_abund_matrix %>%
  ungroup() %>%
  filter(total_abundance >0 ) %>%
  select(-c(year, season, combined_trt, total_plots, total_empty_plots, total_abundance)) %>%
  mutate_all(sqrt)



summer_treat_ca <- cca(summer_treat_abund_matrix)

barplot(summer_treat_ca$CA$eig / summer_treat_ca$tot.chi, names.arg = 1:summer_treat_ca$CA$rank, cex.names = 0.5)

(summer_treat_ca$CA$eig / summer_treat_ca$tot.chi)[1:5]


preds <-  summer_treat_abunds %>%
  ungroup() %>%
  filter(total_abundance > 0) %>%
  select((c(year, combined_trt)))%>%
  mutate(rod_era = as.ordered(ifelse(year < 1997, "a",
                                     ifelse(year < 2010, "b",
                                            "c"))))

summer_treat_ca_scores <- as.data.frame(scores(summer_treat_ca, display = "sites", scaling = "sites")) %>%
  cbind(preds)

ggplot(summer_treat_ca_scores, aes(CA1, CA2, color = rod_era)) + 
  geom_point()  +
  stat_ellipse() +
  facet_wrap(vars(combined_trt))
```