---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("scaffold", "R", "gams_fxns_generalized_re.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>%
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(treatment = ordered(plot_type)) 

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup() 


short_plot_totals <- plot_totals %>%
  mutate(plot = as.factor(plot))

```


```{r}

ggplot(short_plot_totals, aes(period, smgran_e, group = plot, color = treatment)) +
  geom_line()

no_re <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40), family = "tw", data = short_plot_totals)

re <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + s(plot, bs = 're', k = 40) + s(period, by = plot, bs = 're',k= 40), family = "tw", data = short_plot_totals)

re_no_time <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + s(plot, bs = 're'), family = "tw", data = short_plot_totals)

fe <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + plot + s(period, by = plot), family = "tw", data = short_plot_totals)

fe_no_time <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + plot, family = "tw", data = short_plot_totals)

save(no_re, re, re_no_time, fe, fe_no_time, file = "smgran_mods.RData")

load("smgran_mods.RData")
```

```{r}

no_re_pred <- gratia::add_fitted(short_plot_totals, no_re)
re_pred <- gratia::add_fitted(short_plot_totals, re)
re_no_time_pred <- gratia::add_fitted(short_plot_totals, re_no_time)

ggplot(no_re_pred, aes(period, .value, color = treatment, group = plot)) +
  geom_line()

no_re_pdat <- short_plot_totals %>%
  mutate(type = "no_re") %>%
  select(period, treatment, type) %>%
  distinct()

no_re_diff <- get_exclosure_diff(no_re, no_re_pdat, "treatment", comparison_level = 3)

no_re_pred <- get_predicted_vals(no_re, no_re_pred) %>% 
  add_exclosure_diff(no_re_diff)

plot_fitted_pred(no_re_pred)


fe_pred <- gratia::add_fitted(short_plot_totals, fe)

fe_pdat <- short_plot_totals %>%
  mutate(type = "fe") %>%
  select(period, treatment, type, era, plot) %>% 
  filter(plot %in% c(2,3,4)) %>%
  distinct()

fe_diff <- get_exclosure_diff(fe, fe_pdat, "treatment", comparison_level = 3)

fe_pred2 <- get_predicted_vals(fe, fe_pdat) %>% 
  add_exclosure_diff(fe_diff)

fe_diff3 <- get_exclosure_diff(fe, fe_pdat, "treatment", comparison_level = 2)

fe_pred3 <- get_predicted_vals(fe, fe_pdat) %>%
  add_exclosure_diff(fe_diff3)

```

```{r}

ggplot(fe_pred, aes(period, .value, color = treatment, group = plot)) +
  geom_line() +
#  geom_line(data = fe_pred2, aes(period, invlink_fit, color= treatment), inherit.aes = F, size = 2, alpha = .5) +
  scale_color_viridis_d(end = .8)


plot_fitted_pred(filter(fe_pred2, treatment != "CE")) +
  facet_grid(cols =vars(era), scales = "free_x", space = "free")


plot_fitted_pred(filter(fe_pred3, treatment != "EE")) +
  facet_grid(cols =vars(era), scales = "free_x", space = "free") +
  scale_fill_viridis_d(end = .4) +
  scale_color_viridis_d(end = .4)

```

```{r}

library(nlme)
library(lsmeans)
sge_lme <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = short_plot_totals, correlation = corAR1(form = ~period|plot))

sge_lme_no_ac <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = short_plot_totals)

sge_gls <- gls(smgran_e ~ treatment * era, correlation = corAR1(form = ~period|plot), data = short_plot_totals)


sge_gls_noac <- gls(smgran_e ~ treatment * era, data = short_plot_totals)

summary(pairs(lsmeans(sge_lme, specs = ~treatment | era)))

summary(pairs(lsmeans(sge_gls, specs = ~treatment | era)))

```