---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("scaffold", "R", "gams_fxns_generalized_re.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>%
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(treatment = ordered(plot_type)) 

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup() 


short_plot_totals <- plot_totals %>%
  mutate(plot = factor(plot)) %>%
  group_by(treatment, period) %>%
  mutate(mean_sg = mean(smgran_e)) %>%
  ungroup()

```


```{r}

ggplot(short_plot_totals, aes(period, smgran_e, group = plot, color = treatment)) +
  geom_line()
# 
# no_re <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40), family = "tw", data = short_plot_totals)
# 
# re <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + s(plot, bs = 're', k = 40) + s(period, by = plot, bs = 're',k= 40), family = "tw", data = short_plot_totals)
# 
# re_no_time <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + s(plot, bs = 're', k = 40), family = "tw", data = short_plot_totals)
# 
# fe <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + plot + s(period, by = plot, k = 40), family = "tw", data = short_plot_totals)
# 
# fe_no_time <- gam(smgran_e ~ treatment + s(period, k = 40) + s(period, by = treatment, k = 40) + plot, family = "tw", data = short_plot_totals)



```

```{r}

ggplot(filter(short_plot_totals, era == "d_post-switch"), aes(period, smgran_e, color = treatment, group = plot)) +
  geom_line(alpha = .75) +
  geom_line(aes(period, mean_sg)) +
  scale_color_viridis_d(end = .8)

```


<!-- ```{r} -->

<!-- no_re_pred <- gratia::add_fitted(short_plot_totals, no_re) -->
<!-- re_pred <- gratia::add_fitted(short_plot_totals, re) -->
<!-- re_no_time_pred <- gratia::add_fitted(short_plot_totals, re_no_time) -->

<!-- ggplot(no_re_pred, aes(period, .value, color = treatment, group = plot)) + -->
<!--   geom_line() -->

<!-- no_re_pdat <- short_plot_totals %>% -->
<!--   mutate(type = "no_re") %>% -->
<!--   select(period, treatment, type) %>% -->
<!--   distinct() -->

<!-- no_re_diff <- get_exclosure_diff(no_re, no_re_pdat, "treatment", comparison_level = 3) -->

<!-- no_re_pred <- get_predicted_vals(no_re, no_re_pred) %>%  -->
<!--   add_exclosure_diff(no_re_diff) -->

<!-- plot_fitted_pred(no_re_pred) -->


<!-- re_pdat <- short_plot_totals %>% -->
<!--   mutate(type = "re") %>% -->
<!--   select(period, treatment, type, era) %>% -->
<!--   distinct() -->

<!-- re_diff <- get_exclosure_diff(re, re_pdat, "treatment", comparison_level = 3) -->

<!-- re_pred2 <- get_predicted_vals(re, re_pdat) %>%  -->
<!--   add_exclosure_diff(re_diff) -->

<!-- re_diff3 <- get_exclosure_diff(re, re_pdat, "treatment", comparison_level = 2) -->

<!-- re_pred3 <- get_predicted_vals(re, re_pdat) %>% -->
<!--   add_exclosure_diff(re_diff3) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- ggplot(re_pred, aes(period, .value, color = treatment, group = plot)) + -->
<!--   geom_line() + -->
<!--   geom_line(data = re_pred2, aes(period, invlink_fit, color= treatment), inherit.aes = F, size = 2, alpha = .5) + -->
<!--   scale_color_viridis_d(end = .8) -->


<!-- plot_fitted_pred(filter(re_pred2, treatment != "CE")) + -->
<!--   facet_grid(cols =vars(era), scales = "free_x", space = "free") -->


<!-- plot_fitted_pred(filter(re_pred3, treatment != "EE")) + -->
<!--   facet_grid(cols =vars(era), scales = "free_x", space = "free") + -->
<!--   scale_fill_viridis_d(end = .4) + -->
<!--   scale_color_viridis_d(end = .4) -->

<!-- ``` -->

### Linear models

Generalized least squares and linear mixed models, with and without autocorrelation.

```{r}

library(nlme)
library(lsmeans)
sge_lme <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = short_plot_totals, correlation = corCAR1())

sge_lme_no_ac <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = short_plot_totals)

sge_gls <- gls(smgran_e ~ treatment * era, correlation = corCAR1(), data = short_plot_totals)

sge_gls_noac <- gls(smgran_e ~ treatment * era, data = short_plot_totals)

sge_lme_timeac <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = short_plot_totals, correlation = corCAR1(form = ~ period | plot))

sge_gls_timeac <- gls(smgran_e ~ treatment * era, correlation = corCAR1(form = ~ period | plot), data = short_plot_totals)


AIC(sge_lme) # random plot effect and corAR1()
AIC(sge_lme_no_ac) # random plot effect
AIC(sge_gls) # no plot effect and corAR1()
AIC(sge_gls_noac) # no plot effect
AIC(sge_lme_timeac) # random plot effect and corAR1(period)
AIC(sge_gls_timeac) # no plot effect and cor(AR1(period))


summary(pairs(lsmeans(sge_lme_timeac, specs = ~treatment | era)))

summary(pairs(lsmeans(sge_gls_timeac, specs = ~treatment | era)))

```