---
title: "PB"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
       toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.dim =c(8, 4))
library(soar)
library(ggplot2)
library(dplyr)

theme_set(theme_bw())
```

```{r}
plot_ps <- get_plot_totals(use_pre_switch = F, currency = "abundance") %>%
  add_new_pps()


plot_ps_annual <- plot_ps %>%
  mutate(censusyear = as.integer(format.Date(as.Date(censusdate), "%Y"))) %>%
  group_by(censusyear, plot, fplot, oplottype, plot_type, fplottype) %>%
  summarize(mean_new_pp = mean(new_pp)) %>%
  ungroup() %>%
  filter(censusyear != 2012)

ggplot(plot_ps_annual, aes(censusyear, mean_new_pp, group = plot, color = oplottype)) +
  geom_line()

treat_ps_annual <- plot_ps_annual %>%
  group_by(censusyear, oplottype, fplottype) %>%
  summarize(mean_new_pp = mean(mean_new_pp)) %>%
  ungroup()

ggplot(filter(treat_ps_annual, oplottype %in% c("CC", "EE")), aes(censusyear, mean_new_pp, color = oplottype)) +
  geom_line() +
  geom_point() 


library(mgcv)
library(gratia)

new_gam <- gam(mean_new_pp ~ s(censusyear, by = fplottype), data = plot_ps_annual, family = "tw")

new_gam_fit <- plot_ps_annual %>%
  add_fitted(new_gam, exclude = "s(fplot)")


ggplot(new_gam_fit, aes(censusyear, .value, color = oplottype)) +
  geom_line()
new_gam_confint <- confint(new_gam, parm = "s(censusyear)", newdata = plot_ps_annual, transform = T)

ggplot(filter(new_gam_confint, fplottype %in% c("CC", "EE")), aes(censusyear, est, color = fplottype, fill = fplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin  = lower, ymax = upper), alpha = .3)

```

