---
title: "Small granivore energy use"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))
library(soar)
library(ggplot2)
library(dplyr)
library(nlme)
library(emmeans)
theme_set(theme_bw())
```



tg as a % of treatment use

```{r}

treatl <- get_treatment_means() %>%
  mutate(fplottype = as.factor(plot_type))
era_grid <-   facet_grid(cols = vars(oera), space = "free", scales = "free_x")

tg_prop <- treatl %>%
  mutate(tg_prop = tinygran_e / total_e) %>%
  group_by(plot_type) %>%
  mutate(tg_prop_ma = maopts(tg_prop)) %>%
  ungroup()

just_ee <- filter(treatl, oplottype == "EE")

ggplot(tg_prop, aes(censusdate, tg_prop_ma, color = oplottype)) +
  geom_line() +
  era_grid


tg_glm <- glm(tg_prop ~ plot_type * era, data = tg_prop, family = quasibinomial())



plot(pairs(emmeans(tg_glm, specs = ~ era | plot_type)))
#plot(regrid(emmeans(tg_glm, specs = ~ oera | oplottype)))

ilink <- tg_glm$family$linkinv

tg_glm_se <- predict(tg_glm, type = "link", se.fit = T, newdata = tg_prop) %>%
  as.data.frame() %>%
  mutate(est = ilink(fit),
         lower = ilink(fit - 2*se.fit),
         upper = ilink(fit + 2*se.fit),
         period = filter(tg_prop)$period,
         plot_type = filter(tg_prop)$plot_type)
# 
# 
# ggplot(tg_glm_se, aes(period, est, color = oplottype, fill = oplottype)) +
#   geom_line() +
#   geom_ribbon(aes(ymin = lower, ymax= upper), alpha = .3)


tg_glm_se <- tg_glm_se %>%
  right_join(select(tg_prop, oera, plot_type, oplottype, period, censusdate, tg_prop_ma))


ggplot(tg_glm_se, aes(censusdate, est, color = oplottype, fill = oplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax= upper), alpha = .3) +
  geom_line(aes(y = tg_prop_ma)) +
  facet_grid(cols = vars(oera), space = "free_x", scales = "free_x") +
  ylab("tg % of energy use") +
  ggtitle("tg ratio over time") +
  theme(legend.position = "top")

```

tg on non-exclosures v EE

```{r}
tinygran_e_ratio <- treatl %>%
  filter(oplottype != "EE") %>%
  select(period, censusdate, era, oera, plot_type, oplottype, tinygran_e, fplottype) %>%
  left_join(select(just_ee, period, tinygran_e) %>% rename(tinygran_e_e = tinygran_e)) %>%
  mutate(tinygran_e_rat = tinygran_e / tinygran_e_e) %>%
  group_by(period) %>%
  mutate(anyna = any(is.na(tinygran_e_rat)),
         anyinf = any(is.infinite(tinygran_e_rat))) %>%
  ungroup() %>%
  filter(!anyna, !anyinf) %>%
  group_by(oplottype) %>%
  mutate(tinygran_e_rat_ma = maopts(tinygran_e_rat)) %>%
  ungroup()

ggplot(tinygran_e_ratio, aes(censusdate, tinygran_e_rat_ma, color = oplottype)) +
  geom_line() +
  ggtitle("Smgran E ratio, from treatment means") +
  era_grid +
  scale_color_viridis_d(end = .75)


tge_mean_gls <- gls(tinygran_e_rat ~ plot_type * era,  correlation = corCAR1(form = ~ period | plot_type), data = tinygran_e_ratio)

tge_mean_gls_emmeans <- emmeans(tge_mean_gls, specs = ~ era | plot_type)

plot(pairs(tge_mean_gls_emmeans))


tge_mean_pred <- as.data.frame(tge_mean_gls_emmeans) %>%
  right_join(tinygran_e_ratio)
  
ggplot(tge_mean_pred, aes(censusdate, emmean, color = oplottype, fill = oplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = .2) +
  era_grid +
  geom_line(aes(y = tinygran_e_rat_ma)) +
  scale_color_viridis_d(end  = .75) +
  scale_fill_viridis_d(end = .75) +
  ggtitle("Total E on treatments as % of control E") +
  ylab("Treatment E / Control E") +
  theme(legend.position = "top") +
  ylim(0, 2)

```
