---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}


library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(use_christensen_plots = F, return_plot = T, use_pre_switch = F) 
%>%
  
  
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()

treatment_means <- get_rodent_data(use_christensen_plots, F, F) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = as.factor(plot_type))

# treatment_ratios <- get_total_energy_ratios(treatment_means)

```


## Ratios


```{r}
treatment_ratios <- get_total_energy_ratios(treatment_means) 

control_means <- filter(treatment_ratios, plot_type == "CC") %>%
  select(period, censusdate, total_e_c)

plot_ratio_totals <- plot_totals %>%
  left_join(control_means) %>%
  mutate(total_e_of_c = total_e / total_e_c,
    sg_of_c = smgran_e / total_e_c,
         tg_of_c = tinygran_e / total_e_c) %>%
  mutate(total_e_of_c = 0.0000000001 + total_e_of_c,
         sg_of_c = 0.0000000001 + sg_of_c,
         tg_of_c = 0.0000000001 + tg_of_c) %>%
  mutate(fplottype = factor(plot_type))

```

```{r}

ggplot(plot_ratio_totals, aes(censusdate, sg_of_c, color = fplottype, group = plot)) +
  geom_line()

```



```{r}

sg_ratio_gam <- gam(sg_of_c ~ fplottype + s(period, k = 100) + s(period, by = fplottype, k = 100), family = "Gamma", data = plot_ratio_totals)

sg_ratio_pdat <- select(plot_ratio_totals, era, fplottype, period) %>%
  distinct() %>%
  mutate(type = "sgmran")

sg_ratio_pred <- get_predicted_vals(sg_ratio_gam, sg_ratio_pdat)

```

```{r, fig.dim = c(7,7)}
ggplot(sg_ratio_pred, aes(period, invlink_fit, color = fplottype, fill = fplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = invlink_lower, ymax = invlink_upper), alpha = .5) +
  geom_line(data = plot_ratio_totals, aes(x = period, y = sg_of_c, color = fplottype, group = as.factor(plot)), inherit.aes= F) +
  facet_grid(cols = vars(era), rows = vars(fplottype), space = "free", scales = "free")
```

```{r}

sg_ratio_ee_cc_diff <- get_exclosure_diff(sg_ratio_gam, sg_ratio_pred, comparison_variable = "fplottype", comparison_level = 3)

sg_ratio_ee_cc_pred <- add_exclosure_diff(sg_ratio_pred, sg_ratio_ee_cc_diff)

plot_fitted_pred(filter(sg_ratio_ee_cc_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  ggtitle("GAM diff smgran ratio EE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


sg_ratio_ce_cc_diff <- get_exclosure_diff(sg_ratio_gam, sg_ratio_pred, comparison_variable = "fplottype", comparison_level = 2)


sg_ratio_ce_cc_pred <- add_exclosure_diff(sg_ratio_pred, sg_ratio_ce_cc_diff)

plot_fitted_pred(filter(sg_ratio_ce_cc_pred, fplottype != "EE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_fill_viridis_d(end = .4) +
  scale_color_viridis_d(end = .4) +
  ggtitle("GAM diff smgran ratio CE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


sg_ratio_ce_ee_diff <- get_exclosure_diff(sg_ratio_gam, sg_ratio_pred, comparison_variable = "fplottype", comparison_level = 3, reference_level = 2)

sg_ratio_ce_ee_pred <- add_exclosure_diff(sg_ratio_pred, sg_ratio_ce_ee_diff)

plot_fitted_pred(filter(sg_ratio_ce_ee_pred, fplottype != "CC"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  scale_fill_viridis_d(begin = .4, end = .8) +
  scale_color_viridis_d(begin = .4, end = .8) +
  ggtitle("GAM diff smgran ratio CE v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


# 
# ggplot(filter(treatment_ratios_annual, fplottype != "CE"), aes(censusyear, mean_sg_ratio, color = fplottype)) +
#   geom_line() +
#   scale_color_viridis_d(end = .8)

```


```{r}

tg_ratio_gam <- gam(tg_of_c ~ fplottype + s(period, k = 100) + s(period, by = fplottype, k = 100), family = "Gamma", data = plot_ratio_totals)

tg_ratio_pdat <- select(plot_ratio_totals, era, fplottype, period) %>%
  distinct() %>%
  mutate(type = "tinygran")

tg_ratio_pred <- get_predicted_vals(tg_ratio_gam, tg_ratio_pdat)
```

```{r, fig.dim = c(7,7)}
ggplot(tg_ratio_pred, aes(period, invlink_fit, color = fplottype, fill = fplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = invlink_lower, ymax = invlink_upper), alpha = .5) +
  geom_line(data = plot_ratio_totals, aes(x = period, y = tg_of_c, color = fplottype, group = as.factor(plot)), inherit.aes= F) +
  facet_grid(cols = vars(era), rows = vars(fplottype), space = "free", scales = "free")

```

```{r}

tg_ratio_ee_cc_diff <- get_exclosure_diff(tg_ratio_gam, tg_ratio_pred, comparison_variable = "fplottype", comparison_level = 3)

tg_ratio_ee_cc_pred <- add_exclosure_diff(tg_ratio_pred, tg_ratio_ee_cc_diff)

plot_fitted_pred(filter(tg_ratio_ee_cc_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  ggtitle("GAM diff tgran ratio EE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


tg_ratio_ce_cc_diff <- get_exclosure_diff(tg_ratio_gam, tg_ratio_pred, comparison_variable = "fplottype", comparison_level = 2)

tg_ratio_ce_cc_pred <- add_exclosure_diff(tg_ratio_pred, tg_ratio_ce_cc_diff)


plot_fitted_pred(filter(tg_ratio_ce_cc_pred, fplottype != "EE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_fill_viridis_d(end = .4) +
  scale_color_viridis_d(end = .4) +
  ggtitle("GAM diff tgran ratio CE v CC")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")
```

```{r}

tg_ratio_ce_ee_diff <- get_exclosure_diff(tg_ratio_gam, tg_ratio_pred, comparison_variable = "fplottype", comparison_level = 3, reference_level = 2)

tg_ratio_ce_ee_pred <- add_exclosure_diff(tg_ratio_pred, tg_ratio_ce_ee_diff)

plot_fitted_pred(filter(tg_ratio_ce_ee_pred, fplottype != "CC"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) +
  scale_fill_viridis_d(begin = .4, end = .8) +
  scale_color_viridis_d(begin = .4, end = .8) +
  ggtitle("GAM diff tgran ratio CE v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")



# 
# tg_ratio_pred_annual <- tg_ratio_pred %>%
#   left_join(distinct(select(treatment_ratios, period, censusdate))) %>% 
#   mutate(censusdate = as.Date(censusdate)) %>%
#   mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
#   group_by(censusyear, fplottype) %>%
#   summarize(mean_fit = mean(invlink_fit),
#          nperiods = length(unique(period)),
#          nsamples = dplyr::n()) %>%
#   ungroup()
# 
#   
# 
# ggplot(filter(treatment_ratios_annual, fplottype != "CE"), aes(censusyear, mean_tg_ratio, color = fplottype)) +
#   geom_line() +
#   scale_color_viridis_d(end = .8) +
#   geom_line(data = filter(tg_ratio_pred_annual, fplottype != "CE"), aes(censusyear, mean_fit))

```

```{r}

total_ratio_gam <- gam(total_e_of_c ~ fplottype + s(period, k = 100) + s(period, by = fplottype, k = 100), family = "Gamma", data = filter(plot_ratio_totals, fplottype != "CC"))

total_ratio_pdat <- select(plot_ratio_totals, era, 
                          fplottype, period) %>%
  mutate(type = "all_energy") %>%
  filter(fplottype != "CC") %>%
  distinct()

total_e_ratio_pred <- get_predicted_vals(total_ratio_gam, total_ratio_pdat)
```

```{r, fig.dim = c(7,7)}


ggplot(total_e_ratio_pred, aes(period, invlink_fit, color = fplottype, fill = fplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = invlink_lower, ymax = invlink_upper), alpha = .5) +
  geom_line(data = plot_ratio_totals, aes(x = period, y = total_e_of_c, color = fplottype, group = as.factor(plot)), inherit.aes= F) +
  facet_grid(cols = vars(era), rows = vars(fplottype), space = "free", scales = "free")

```

```{r}

total_e_ratio_diff <- get_exclosure_diff(total_ratio_gam, total_ratio_pdat, comparison_variable = "fplottype", comparison_level = 3, reference_level = 2)
total_e_ratio_pred <- add_exclosure_diff(total_e_ratio_pred, total_e_ratio_diff)

plot_fitted_pred(filter(total_e_ratio_pred), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_color_viridis_d(begin = .4, end = .8) +
  scale_fill_viridis_d(begin = .4, end = .8) +
  ggtitle("Total energy ratio fits + diff, CE v EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")


plot_fitted_pred(filter(select(total_e_ratio_pred, -diff_overlaps_zero), fplottype == "EE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_color_viridis_d(begin = .8, end = .8) +
  scale_fill_viridis_d(begin = .8, end = .8) +
  ggtitle("Total energy ratio fit, EE")+
  facet_grid(cols = vars(era), scales = "free_x", space = "free") +
  theme(legend.position = "top")

```

## By era

##### Era means:

```{r}

era_means <- treatment_means %>%
  group_by(era, plot_type) %>%
  mutate(total_e_mean = mean(total_e),
         smgran_e_mean = mean(smgran_e),
         tinygran_e_mean = mean(tinygran_e)) %>%
  ungroup()
# 
# ggplot(era_means, aes(period, total_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, total_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 
# 
# ggplot(era_means, aes(period, smgran_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, smgran_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)
# 
# 
# 
# ggplot(era_means, aes(period, tinygran_e_mean, color = oplottype)) +
#   geom_line(size = 2) +
#   geom_line(aes(period, tinygran_e), alpha = .3) +
#   scale_color_viridis_d(end = .8)

select(era_means, era, oplottype, total_e_mean, smgran_e_mean, tinygran_e_mean) %>%
  distinct()


save.image('byplot.RData')

```

<!-- ### gls on ratios -->

<!-- ##### Era ratios: -->

<!-- ```{r} -->

<!-- era_ratios <- treatment_ratios
<!--   group_by(era, oplottype) %>% -->
<!--   mutate(te_mean = mean(total_e_of_c), -->
<!--          sg_mean = mean(sg_of_c), -->
<!--          tg_mean = mean(tg_of_c)) %>% -->
<!--   ungroup() -->


<!-- select(era_ratios, era, oplottype, te_mean, sg_mean, tg_mean) %>% -->
<!--   distinct() -->

<!-- ggplot(era_ratios, aes(period, te_mean, color = oplottype)) + -->
<!--   geom_line(size = 2) + -->
<!--   geom_line(aes(period, total_e_of_c), alpha = .3) + -->
<!--   scale_color_viridis_d(end = .8) -->


<!-- # ggplot(era_ratios, aes(period, sg_mean, color = oplottype)) + -->
<!-- #   geom_line(size = 2) + -->
<!-- #   geom_line(aes(period, sg_of_c), alpha = .3) + -->
<!-- #   scale_color_viridis_d(end = .8) -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # ggplot(era_ratios, aes(period, tg_mean, color = oplottype)) + -->
<!-- #   geom_line(size = 2) + -->
<!-- #   geom_line(aes(period, tg_of_c), alpha = .3) + -->
<!-- #   scale_color_viridis_d(end = .8) -->
<!-- #  -->

<!-- treatment_ratios_no_c <- filter(treatment_ratios, fplottype != "CC") %>% -->
<!--   mutate(fplottype = as.factor(plot_type)) -->
<!-- ``` -->

<!-- ##### Total energy ratios GLS -->

<!-- This fit includes CC plots, for which ratio always = 1.  -->

<!-- ```{r} -->
<!-- ter_gls <- gls(total_e_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype)) -->
<!-- summary(pairs(lsmeans(ter_gls, specs = ~fplottype | era))) -->

<!-- ``` -->

<!-- This fit has CC plots removed. -->

<!-- ```{r} -->
<!-- ter_gls <- gls(total_e_of_c ~ era * fplottype, data = treatment_ratios_no_c, correlation = corAR1(form = ~period|fplottype)) -->
<!-- summary(pairs(lsmeans(ter_gls, specs = ~fplottype | era))) -->
<!-- summary(pairs(lsmeans(ter_gls, specs = ~era | fplottype))) -->

<!-- ``` -->

<!-- ##### Smgran ratio GLS -->

<!-- ```{r} -->
<!-- sgr_gls <- gls(sg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype)) -->
<!-- summary(pairs(lsmeans(sgr_gls, specs = ~fplottype | era))) -->

<!-- ``` -->

<!-- ##### Tiny gran ratio GLS -->

<!-- ```{r} -->
<!-- tgr_gls <- gls(tg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype)) -->
<!-- summary(pairs(lsmeans(tgr_gls, specs = ~fplottype | era))) -->

<!-- ``` -->



<!-- ### glm on ratios -->

<!-- ##### Total energy GLM -->

<!-- With  controls: -->

<!-- ```{r} -->

<!-- ter_glm <- gam(total_e_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma") -->
<!-- summary(pairs(regrid(lsmeans(ter_glm, specs = ~fplottype | era)))) -->
<!-- ``` -->

<!-- Without controls: -->

<!-- ```{r} -->

<!-- ter_glm <- gam(total_e_of_c ~ era * fplottype, data = treatment_ratios_no_c, family = "Gamma") -->
<!-- summary(pairs(regrid(lsmeans(ter_glm, specs = ~fplottype | era)))) -->


<!-- ``` -->

<!-- ##### Small granivore ratio GLM -->

<!-- ```{r} -->
<!-- sgr_glm <- gam(sg_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma") -->
<!-- #summary(pairs(lsmeans(sgr_glm, specs = ~fplottype | era))) -->
<!-- summary(pairs(regrid(lsmeans(sgr_glm, specs = ~fplottype | era)))) -->
<!-- ``` -->


<!-- ##### Tiny granivore ratio GLM -->

<!-- ```{r} -->
<!-- tgr_glm <- gam(tg_of_c ~ era * fplottype, data = treatment_ratios, family = "Gamma") -->
<!-- summary(pairs(regrid(lsmeans(tgr_glm, specs = ~fplottype | era)))) -->

<!-- ``` -->