---
title: "1981 analysis with GAMs"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 4, fig.height=3)
rats <- read.csv(here::here("lore", "1981_competition", "1981_data_complete.csv"), stringsAsFactors = F)
rat_totals <- read.csv(here::here("lore", "1981_competition", "1981_data_statevars.csv"), stringsAsFactors = F)
rat_plot_totals <- read.csv(here::here("lore", "1981_competition", "1981_data_plot_totals.csv"), stringsAsFactors = F)
library(dplyr)
library(mgcv)
library(ggplot2)
source(here::here("lore", "1981_competition", "gams_fxns.R"))



rat_totals <- rat_totals %>%
  mutate(krat_treatment = ifelse(brown_trtmnt == "dipo_present", "control", "exclosure")) %>%
  mutate(okrat_treatment = ordered(krat_treatment))


rat_plot_totals <- rat_plot_totals %>%
    mutate(krat_treatment = ifelse(brown_trtmnt == "dipo_present", "control", "exclosure")) %>%
  mutate(okrat_treatment = ordered(krat_treatment)) %>%
  mutate(oplot = ordered(plot))

```


```{r sg}
sg <- filter(rat_totals, type == "small_granivore")

print(plot_orig_data(sg))

sg_plot <- filter(rat_plot_totals, type == "small_granivore")

print(plot_orig_data(sg_plot) + facet_wrap(vars(plot)))


sg.gam <- gam(nind ~ okrat_treatment + s(period) + s(period, by = okrat_treatment) + oplot + s(period, by = oplot), data = sg_plot, family = poisson, method = "REML")

summary(sg.gam)


sg.pdat <- make_pdat(sg_plot, include_plot = T)
sg.pred <- get_predicted_vals(sg.gam, sg.pdat)

sg.diff <- get_exclosure_diff(sg.gam, sg.pdat)

print(plot_exclosure_diff(sg.diff))

sg.pred <- add_exclosure_diff(sg.pred, sg.diff)

print(plot_link_pred(sg.pred))

print(plot_fitted_pred(sg.pred))

```

```{r sg no plot}
sg.gam <- gam(nind ~ okrat_treatment + s(period) + s(period, by = okrat_treatment), data = sg, family = poisson, method = "REML")

summary(sg.gam)


sg.pdat <- make_pdat(sg, include_plot = F)
sg.pred <- get_predicted_vals(sg.gam, sg.pdat)

sg.diff <- get_exclosure_diff(sg.gam, sg.pdat)

print(plot_exclosure_diff(sg.diff))

sg.pred <- add_exclosure_diff(sg.pred, sg.diff)

print(plot_link_pred(sg.pred))

print(plot_fitted_pred(sg.pred))

```


```{r sg no plot but plot level}
sg.gam <- gam(nind ~ okrat_treatment + s(period) + s(period, by = okrat_treatment), data = sg_plot, family = poisson, method = "REML")

summary(sg.gam)


sg.pdat <- make_pdat(sg_plot, include_plot = F)
sg.pred <- get_predicted_vals(sg.gam, sg.pdat)

sg.diff <- get_exclosure_diff(sg.gam, sg.pdat)

print(plot_exclosure_diff(sg.diff))

sg.pred <- add_exclosure_diff(sg.pred, sg.diff)

print(plot_link_pred(sg.pred))

print(plot_fitted_pred(sg.pred))

```