---
title: "hold this loosely..."
output:
       github_document:
       df_print: kable
       toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))
library(soar)
library(ggplot2)
library(dplyr)
library(mgcv)
library(gratia)
theme_set(theme_bw())

library(nlme)
library(emmeans)

```


```{r}

treatl <- get_treatment_means() %>%
  mutate(fplottype = as.factor(plot_type),
         pb_prop = pb_e / total_e) %>%
  group_by(oplottype) %>%
  mutate(pb_prop_ma = maopts(pb_prop)) %>%
  ungroup()

era_grid <-   facet_grid(cols = vars(oera), space = "free", scales = "free_x")


just_controls <- filter(treatl, oplottype == "CC")

zero_to_one <- function(val) {
  if(val == 0) {
    return(1)
  }
  return(val)
}

e_ratios <- treatl %>%
  filter(oplottype != "CC") %>%
  select(period, censusdate, era, oera, plot_type, oplottype, total_e, smgran_e, tinygran_e, fplottype) %>%
  left_join(select(just_controls, period, total_e, smgran_e, tinygran_e) %>%  rename(total_e_c = total_e, smgran_e_c = smgran_e, tinygran_e_c = tinygran_e)) %>%
  mutate(total_e_rat = total_e / total_e_c,
         smgran_e_rat = smgran_e / smgran_e_c,
         tinygran_e_rat = tinygran_e / tinygran_e_c) %>%
  group_by(oplottype) %>%
  mutate(total_e_rat_ma = maopts(total_e_rat),
         smgran_e_rat_ma = maopts(smgran_e_rat),
         tinygran_e_rat_ma = maopts(tinygran_e_rat)) %>%
  ungroup()

smgrane_logratio <- treatl %>%
  filter(oplottype != "CC") %>%
  select(period, censusdate, era, oera, plot_type, oplottype, smgran_e, fplottype) %>%
  left_join(select(just_controls, period, smgran_e) %>%  rename(smgran_e_c = smgran_e)) %>%
  mutate(smgran_e_lograt = log(smgran_e / smgran_e_c)) %>%
  group_by(period) %>%
  mutate(anyinf = any(is.infinite(smgran_e_lograt)),
         anyna = any(is.na(smgran_e_lograt))) %>%
  ungroup() %>%
  filter(!anyinf, !anyna) %>%
  group_by(oplottype) %>%
  mutate(smgran_e_lograt_ma = maopts(smgran_e_lograt)) %>%
  ungroup()


ggplot(smgrane_logratio, aes(censusdate, (smgran_e_lograt_ma), color = oplottype)) +
  geom_line() +
  ggtitle("smgran E log ratio, from treatment means") +
  era_grid

smgrane_logratio_interp <- treatl %>%
  filter(oplottype != "CC") %>%
  select(period, censusdate, era, oera, plot_type, oplottype, smgran_e, fplottype) %>%
  left_join(select(just_controls, period, smgran_e) %>%  rename(smgran_e_c = smgran_e)) %>%
  group_by_all() %>%
  mutate_at(c("smgran_e", "smgran_e_c"), .funs = zero_to_one) %>%
  ungroup() %>%
  mutate(smgran_e_lograt = log(smgran_e / smgran_e_c)) %>%
  group_by(oplottype) %>%
  mutate(smgran_e_lograt_ma = maopts(smgran_e_lograt)) %>%
  ungroup()

ggplot(smgrane_logratio_interp, aes(censusdate, (smgran_e_lograt_ma), color = oplottype)) +
  geom_line() +
  ggtitle("smgran E log ratio, from treatment means, interpolating 0s") +
  era_grid

```

# smgran E models

## Not log ratio

```{r}

e_ratios_sg <- e_ratios %>%
  group_by(period) %>%
  mutate(anyinf = any(is.infinite(smgran_e_rat)),
         anyna = any(is.na(smgran_e_rat))) %>%
  ungroup() %>%
  filter(!anyinf, !anyna) %>%
  group_by(plot_type) %>%
  mutate(smgran_e_rat_ma = maopts(smgran_e_rat_ma))
  

smgrane_mean_gls <- gls(smgran_e_rat ~ plot_type * era,  correlation = corCAR1(form = ~ period | plot_type), data = e_ratios_sg)

smgrane_mean_gls_emmeans <- emmeans(smgrane_mean_gls, specs = ~ era | plot_type)

notlog_pairs <- as.data.frame(pairs(smgrane_mean_gls_emmeans))


smgrane_mean_pred <- as.data.frame(smgrane_mean_gls_emmeans) %>%
  right_join(e_ratios_sg)

ggplot(smgrane_mean_pred, aes(censusdate, emmean, color = oplottype, fill = oplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = .2) +
  era_grid +
  geom_line(aes(y = smgran_e_rat)) +
  scale_color_viridis_d(begin  = .25) +
  scale_fill_viridis_d(begin = .25) +
  ggtitle("smgran E on treatments as % of control E") +
  ylab("Treatment E / Control E") +
  theme(legend.position = "top")

```

## Log ratio


```{r}

smgrane_lr_gls <- gls(smgran_e_lograt ~ plot_type * era,  correlation = corCAR1(form = ~ period | plot_type), data = smgrane_logratio)

smgrane_lr_gls_emmeans <- emmeans(smgrane_lr_gls, specs = ~ era | plot_type)

lr_pairs <- as.data.frame(pairs(smgrane_lr_gls_emmeans))

smgrane_lr_pred <- as.data.frame(smgrane_lr_gls_emmeans) %>%
  right_join(smgrane_logratio) %>%
  mutate_at(c("emmean", "lower.CL", "upper.CL", "smgran_e_lograt_ma"), .funs = exp)

ggplot(smgrane_lr_pred, aes(censusdate, emmean, color = oplottype, fill = oplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = .2) +
  era_grid +
geom_line(aes(y = smgran_e_lograt_ma)) +
  scale_color_viridis_d(begin  = .25) +
  scale_fill_viridis_d(begin = .25) +
  ggtitle("smgran E on treatments as % of control E") +
  ylab("Treatment E / Control E") +
  theme(legend.position = "top")

```

## Log ratio interpolating


```{r}

smgrane_lr_i_gls <- gls(smgran_e_lograt ~ plot_type * era,  correlation = corCAR1(form = ~ period | plot_type), data = smgrane_logratio_interp)

smgrane_lr_i_gls_emmeans <- emmeans(smgrane_lr_i_gls, specs = ~ era | plot_type)

lr_i_pairs <- as.data.frame(pairs(smgrane_lr_i_gls_emmeans))

smgrane_lr_i_pred <- as.data.frame(smgrane_lr_i_gls_emmeans) %>%
  right_join(smgrane_logratio_interp) %>%
  mutate_at(c("emmean", "lower.CL", "upper.CL", "smgran_e_lograt_ma"), .funs = exp)

ggplot(smgrane_lr_i_pred, aes(censusdate, emmean, color = oplottype, fill = oplottype)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = .2) +
  era_grid +
geom_line(aes(y = smgran_e_lograt_ma)) +
  scale_color_viridis_d(begin  = .25) +
  scale_fill_viridis_d(begin = .25) +
  ggtitle("smgran E on treatments as % of control E") +
  ylab("Treatment E / Control E") +
  theme(legend.position = "top")

```

## Significance comparison

```{r}

is_sig <- function(pval) {
  return(pval < .05)
}

pairs_df <- bind_rows(
  notlog = notlog_pairs,
  lr = lr_pairs,
  lr_i = lr_i_pairs,
  .id = "mod"
) %>% 
  mutate(sig = is_sig(p.value))

ggplot(pairs_df, aes(contrast, mod, color = sig)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(vars(plot_type))

```