---
title: "to 2015"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)

```

```{r}
rats <- read.csv(here::here("lore", "2020_redux", "2020_data_complete.csv"))

```

```{r}

pb <- rats %>%
  filter(species == "PB") %>%
  select(period, censusdate, plot, treatment, energy) %>%
  group_by(period, censusdate, plot, treatment) %>%
  summarize(nind = dplyr::n(),
            energy = sum(energy)) %>%
  ungroup() %>%
  mutate(censusdate = as.Date(censusdate))

pb_all_periods <- expand.grid(period = unique(rats$period),
                              plot = unique(rats$plot)) %>%
  left_join(distinct(select(rats, period, censusdate))) %>%
  left_join(distinct(select(rats, plot, treatment))) %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  left_join(pb) %>%
  mutate(energy = ifelse(is.na(energy), 0, energy),
         nind = ifelse(is.na(nind), 0, nind))

ggplot(filter(pb_all_periods), aes(censusdate, nind, group = plot, color = treatment)) +
  geom_smooth(method = "gam", se = F, size = 2, method.args = list(family = "poisson")) +
  #geom_line()+
  theme_bw() +
  scale_color_viridis_d(end = .8) +
  scale_x_date(date_breaks = "9 month", date_labels =  "%b %Y") +
  theme(axis.text.x=element_text(angle=60, hjust=1))

```


```{r}


library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

pb_all_periods <- pb_all_periods %>%
  mutate(oplot = ordered(plot, levels = c(4,2,3,8,11,14,15,17,18,21,22)),
         treatment = as.ordered(treatment)) %>%
  as.data.frame() %>%
  filter(period > 215)

pb.mod <- gam(nind ~  treatment + s(period) + s(period, by = treatment) + plot + s(period, by = plot), family = "poisson", data  = pb_all_periods, method = "REML")

gam.check(pb.mod)

pb.pdat <- make_pdat(pb_all_periods, include_plot = T)

pb.pdat <- pb.pdat %>%
  mutate(type = "pb",
         plot = 4)

pb.pred <- get_predicted_vals(pb.mod, pb.pdat)

plot_fitted_pred(pb.pred)


ctrl_v_orig <- get_exclosure_diff(pb.mod, pb.pdat, comparison_level = 3)

plot_exclosure_diff(ctrl_v_orig)


ctrl_v_new <- get_exclosure_diff(pb.mod, pb.pdat)

plot_exclosure_diff(ctrl_v_new)

```