---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) 
plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()

treatment_means <- get_rodent_data(use_christensen_plots, F, F) 

treatment_ratios <- get_total_energy_ratios(treatment_means)

```

```{r}

era_lines <- c(216, 356, 434)
tm <- treatment_ratios %>%
  mutate(oplottype = ordered(plot_type)) %>%
  mutate(type = "rats") %>%
  mutate(total_e_of_c = total_e_of_c + .0000000000001,
         all_smgran_of_c = (0.0000000000001) + (smgran_e / total_e_c),
         pb_of_c = (0.0000000000001) + (pb_e / total_e_c),
         not_pb_smgran_of_c = (0.0000000000001) + ((smgran_e - pb_e) / total_e_c))

te.mod <- gam(formula = total_e_of_c ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 40), data  = tm, family = "Gamma")


te.pdat <- expand.grid(period = unique(tm$period),
                      oplottype = levels(tm$oplottype))

te.pred <- get_predicted_vals(te.mod, te.pdat)  %>%
  mutate(era = NA) %>%
  mutate(era = ifelse(period <= 216, "a_pre_ba",
           ifelse(period <= 356, "b_pre_cpt",
                  ifelse(period <= 434, "c_pre_switch", "d_post-switch")))) %>%
  mutate(oera = as.ordered(era))

plot_fitted_pred(filter(te.pred, oplottype != "CE"), comparison_variable = "oplottype") + ylab("Energy use : E on control plots") +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  ggtitle("Total energy use on treatment plots relative to controls") +
  xlim(0, 430)

ggplot(tm, aes(period, total_e_of_c, color = oplottype)) +
  geom_line() +
  facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  scale_color_viridis_d(end = .8) +
  ggtitle("Total energy use on treatment plots relative to control plots")
```

```{r}

asge.mod <- gam(formula = all_smgran_of_c ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 40), data  = tm, family = "Gamma")


asge.pdat <- expand.grid(period = unique(tm$period),
                      oplottype = levels(tm$oplottype))

asge.pred <- get_predicted_vals(asge.mod, asge.pdat)  %>%
  mutate(era = NA) %>%
  mutate(era = ifelse(period <= 216, "a_pre_ba",
           ifelse(period <= 356, "b_pre_cpt",
                  ifelse(period <= 434, "c_pre_switch", "d_post-switch")))) %>%
  mutate(oera = as.ordered(era))

plot_fitted_pred(filter(asge.pred, oplottype != "CE"), comparison_variable = "oplottype") + ylab("Energy use : E on control plots") +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  ggtitle("Non-Dipo energy use on treatment plots relative to controls") 

ggplot(tm, aes(period, all_smgran_of_c, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  scale_color_viridis_d(end = .8) +
  ggtitle("Non-Dipo energy use on treatment plots relative to control plots") +
  xlim(0, 430)

```


```{r}

asge.mod <- gam(formula = all_smgran_of_c ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 40), data  = tm, family = "Gamma")


asge.pdat <- expand.grid(period = unique(tm$period),
                      oplottype = levels(tm$oplottype))

asge.pred <- get_predicted_vals(asge.mod, asge.pdat)  %>%
  mutate(era = NA) %>%
  mutate(era = ifelse(period <= 216, "a_pre_ba",
           ifelse(period <= 356, "b_pre_cpt",
                  ifelse(period <= 434, "c_pre_switch", "d_post-switch")))) %>%
  mutate(oera = as.ordered(era))

plot_fitted_pred(filter(asge.pred, oplottype != "CE"), comparison_variable = "oplottype") + ylab("Energy use : E on control plots") +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  ggtitle("Non-Dipo energy use on treatment plots relative to controls") 
  #geom_vline(xintercept = era_lines)

ggplot(tm, aes(period, all_smgran_of_c, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  scale_color_viridis_d(end = .8) +
  ggtitle("Non-Dipo energy use on treatment plots relative to control plots")

```


```{r}

pbe.mod <- gam(formula = pb_of_c ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 40), data  = filter(tm, period > 200), family = "Gamma")


pbe.pdat <- expand.grid(period = unique(tm$period),
                      oplottype = levels(tm$oplottype)) %>%
  filter(period > 200)

pbe.pred <- get_predicted_vals(pbe.mod, pbe.pdat)  %>%
  mutate(era = NA) %>%
  mutate(era = ifelse(period <= 216, "a_pre_ba",
           ifelse(period <= 356, "b_pre_cpt",
                  ifelse(period <= 434, "c_pre_switch", "d_post-switch")))) %>%
  mutate(oera = as.ordered(era))

plot_fitted_pred(filter(pbe.pred, oplottype != "CE"), comparison_variable = "oplottype") + ylab("Energy use : E on control plots") +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  ggtitle("PB energy use on treatment plots relative to controls") 
 

ggplot(tm, aes(period, pb_of_c, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  scale_color_viridis_d(end = .8) +
  ggtitle("PB energy use on treatment plots relative to control plots") 

```


```{r}

npbe.mod <- gam(formula = not_pb_smgran_of_c ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 40), data  = tm, family = "Gamma")


npbe.pdat <- expand.grid(period = unique(tm$period),
                      oplottype = levels(tm$oplottype))

npbe.pred <- get_predicted_vals(npbe.mod, npbe.pdat)  %>%
  mutate(era = NA) %>%
  mutate(era = ifelse(period <= 216, "a_pre_ba",
           ifelse(period <= 356, "b_pre_cpt",
                  ifelse(period <= 434, "c_pre_switch", "d_post-switch")))) %>%
  mutate(oera = as.ordered(era))

plot_fitted_pred(filter(npbe.pred, oplottype != "CE"), comparison_variable = "oplottype") + ylab("Energy use : E on control plots") +
  #facet_wrap(vars(era), scales = "free_x", nrow = 1) +
  ggtitle("Not-PB small granivore energy use on treatment plots relative to controls")
ggplot(tm, aes(period, not_pb_smgran_of_c, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(era),qq scales = "free_x", nrow = 1) +
  scale_color_viridis_d(end = .8) +
  ggtitle("Not-PB small gran energy use on treatment plots relative to control plots") +
  xlim(0, 430)

```

```{r}

te.pred.bygroup <- te.pred %>%
  left_join(rename(select(pbe.pred, period, oplottype, invlink_fit), pb_fit = invlink_fit)) %>%
  left_join(rename(select(npbe.pred, period, oplottype, invlink_fit), npb_fit = invlink_fit))

ggplot(filter(te.pred.bygroup, oplottype == "EE"), aes(period, invlink_fit, color = oplottype)) +
  geom_line(size = 3, alpha = .25) +
  geom_line(aes(period, pb_fit + npb_fit), linetype = 4, size= 1.5) +
  geom_line(aes(period, npb_fit), linetype = 5, size = 1.5) +
  scale_color_viridis_d(begin = .8, end =.8) +
  scale_fill_viridis_d(begin = .8, end =.8) +
  ylab("Energy use relative to total control energy use") +
  ggtitle("Compensation by PB, other smgran on exclosures") +
  theme(legend.position = "none") 

ggplot(filter(te.pred.bygroup, oplottype == "CC"), aes(period, invlink_fit, color = oplottype)) +
  geom_line(size = 3, alpha = .25) +
  geom_line(aes(period, pb_fit + npb_fit), linetype = 4, size= 1.5) +
  geom_line(aes(period, npb_fit), linetype = 5, size = 1.5) +
  scale_color_viridis_d(begin = 0, end =.0) +
  ylab("Energy use relative to total control energy use") +
  ggtitle("Energy use by PB, other smgran on controls") +
  theme(legend.position = "none")
```

