---
title: "Linear models"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
library(nlme)
library(lsmeans)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

<!-- ```{r} -->

<!-- use_christensen_plots <- F -->

<!-- plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>% -->
<!--    mutate(tinygran_e = smgran_e - pb_e) %>% -->
<!--   mutate(treatment = ordered(plot_type), -->
<!--          plot = ordered(plot)) %>% -->
<!--   mutate(censusdate = as.Date(censusdate)) %>% -->
<!--   mutate(numericdate = as.numeric(censusdate) / 1000) -->

<!-- ``` -->

<!-- Generalized least squares and linear mixed models, with and without autocorrelation. -->

<!-- # Total energy -->

<!-- ```{r} -->

<!-- #te_lme <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1()) -->

<!-- te_lme_no_ac <- lme(total_e ~ treatment * era, random = ~1|plot, data = plot_totals) -->

<!-- #te_gls <- gls(total_e ~ treatment * era, correlation = corCAR1(), data = plot_totals) -->

<!-- te_gls_noac <- gls(total_e ~ treatment * era, data = plot_totals) -->

<!-- te_lme_timeac <- lme(total_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1(form = ~ numericdate | plot)) -->

<!-- te_gls_timeac <- gls(total_e ~ treatment * era, correlation = corCAR1(form = ~ numericdate | plot), data = plot_totals) -->


<!-- #AIC(te_lme) # random plot effect and corAR1() -->
<!-- AIC(te_lme_no_ac) # random plot effect -->
<!-- #AIC(te_gls) # no plot effect and corAR1() -->
<!-- AIC(te_gls_noac) # no plot effect -->
<!-- AIC(te_lme_timeac) # random plot effect and corAR1(period) -->
<!-- AIC(te_gls_timeac) # no plot effect and cor(AR1(period)) -->


<!-- summary(pairs(lsmeans(te_lme_timeac, specs = ~treatment | era))) -->

<!-- #summary(pairs(lsmeans(te_gls_timeac, specs = ~treatment | era))) -->

<!-- ``` -->

<!-- # Small granivores -->

<!-- ```{r} -->

<!-- #sge_lme <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1()) -->

<!-- sge_lme_no_ac <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = plot_totals) -->

<!-- #sge_gls <- gls(smgran_e ~ treatment * era, correlation = corCAR1(), data = plot_totals) -->

<!-- sge_gls_noac <- gls(smgran_e ~ treatment * era, data = plot_totals) -->

<!-- sge_lme_timeac <- lme(smgran_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1(form = ~ numericdate | plot)) -->

<!-- sge_gls_timeac <- gls(smgran_e ~ treatment * era, correlation = corCAR1(form = ~ numericdate | plot), data = plot_totals) -->


<!-- #AIC(sge_lme) # random plot effect and corAR1() -->
<!-- AIC(sge_lme_no_ac) # random plot effect -->
<!-- #AIC(sge_gls) # no plot effect and corAR1() -->
<!-- AIC(sge_gls_noac) # no plot effect -->
<!-- AIC(sge_lme_timeac) # random plot effect and corAR1(period) -->
<!-- AIC(sge_gls_timeac) # no plot effect and cor(AR1(period)) -->


<!-- summary(pairs(lsmeans(sge_lme_timeac, specs = ~treatment | era))) -->

<!-- #summary(pairs(lsmeans(sge_gls_timeac, specs = ~treatment | era))) -->

<!-- ``` -->

<!-- # PB -->

<!-- ```{r} -->

<!-- pb_totals <- filter(plot_totals, era != "a_pre_ba") -->

<!-- pbe_lme_no_ac <- lme(pb_e ~ treatment * era, random = ~1|plot, data = pb_totals) -->

<!-- pbe_gls_noac <- gls(pb_e ~ treatment * era, data = pb_totals) -->

<!-- pbe_lme_timeac <- lme(pb_e ~ treatment * era, random = ~1|plot, data = pb_totals, correlation = corCAR1(form = ~ numericdate | plot)) -->

<!-- pbe_gls_timeac <- gls(pb_e ~ treatment * era, correlation = corCAR1(form = ~ numericdate | plot), data = pb_totals) -->

<!-- save(pb_totals, pbe_lme_no_ac, pbe_gls_noac, pbe_lme_timeac, pbe_gls_timeac, file = "pb_lmes.RData") -->

<!-- ``` -->

<!-- # Tiny granivores -->

<!-- ```{r} -->

<!-- #tge_lme <- lme(tinygran_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1()) -->

<!-- tge_lme_no_ac <- lme(tinygran_e ~ treatment * era, random = ~1|plot, data = plot_totals) -->

<!-- #tge_gls <- gls(tinygran_e ~ treatment * era, correlation = corCAR1(), data = plot_totals) -->

<!-- tge_gls_noac <- gls(tinygran_e ~ treatment * era, data = plot_totals) -->

<!-- tge_lme_timeac <- lme(tinygran_e ~ treatment * era, random = ~1|plot, data = plot_totals, correlation = corCAR1(form = ~ numericdate | plot)) -->

<!-- tge_gls_timeac <- gls(tinygran_e ~ treatment * era, correlation = corCAR1(form = ~ numericdate | plot), data = plot_totals) -->


<!-- #AIC(tge_lme) # random plot effect and corAR1() -->
<!-- AIC(tge_lme_no_ac) # random plot effect -->
<!-- #AIC(tge_gls) # no plot effect and corAR1() -->
<!-- AIC(tge_gls_noac) # no plot effect -->
<!-- AIC(tge_lme_timeac) # random plot effect and corAR1(period) -->
<!-- AIC(tge_gls_timeac) # no plot effect and cor(AR1(period)) -->


<!-- summary(pairs(lsmeans(tge_lme_timeac, specs = ~treatment | era))) -->

<!-- #summary(pairs(lsmeans(tge_gls_timeac, specs = ~treatment | era))) -->
<!-- save.image("lmes.RData") -->
<!-- ``` -->


```{r}
load(here::here("scaffold", "Reports", "lmes.RData"))
load(here::here("scaffold", "Reports", "pb_lmes.RData"))

```


```{r}
te_AICs <- lapply(list(te_gls_noac, te_gls_timeac, te_lme_no_ac, te_lme_timeac), FUN = AIC)
te_AICs

anova(te_gls_timeac, te_lme_timeac)

library(emmeans)

te_emmeans <- emmeans(te_lme_timeac, specs = ~ treatment | era)

pairs(te_emmeans, adjust = "bonf")


te_gls_emmeans <- emmeans(te_gls_timeac, specs = ~ treatment | era)

pairs(te_gls_emmeans, adjust = "bonf")

te_pred <- predict(te_emmeans, interval = "confidence") 

ggplot(te_pred, aes(treatment, emmean, color = treatment)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL)) +
  facet_grid(cols = vars(era))

library(lme4)


te_glmer <- glmer(ceiling(total_e) ~ treatment * era + (1|plot), data =plot_totals, family = poisson)

te_glmer_emmeans <- emmeans(te_glmer, specs = ~  treatment | era)

pairs(te_glmer_emmeans)

te_glmer_pred <- predict(te_glmer_emmeans, interval = "confidence", type = "response")

ggplot(te_glmer_pred, aes(treatment, response)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
  facet_wrap(vars(era))

```



```{r}
sg_AICs <- lapply(list(sge_gls_noac, sge_gls_timeac, sge_lme_no_ac, sge_lme_timeac), FUN = AIC)
sg_AICs

anova(sge_gls_timeac, sge_lme_timeac)

sg_emmeans <- emmeans(sge_lme_timeac, specs = ~ treatment | era)

pairs(sg_emmeans, adjust = "bonf")

sg_gls_emmeans <- emmeans(sge_gls_timeac, specs = ~ treatment | era)

pairs(sg_gls_emmeans, adjust = "bonf")


sg_pred <- predict(sg_emmeans, interval = "confidence") 

ggplot(sg_pred, aes(treatment, emmean, color = treatment)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL)) +
  facet_grid(cols = vars(era))

sg_glmer <- glmer(ceiling(smgran_e) ~ treatment * era + (1|plot), data =plot_totals, family = poisson)

sg_glmer_emmeans <- emmeans(sg_glmer, specs = ~  treatment | era)

pairs(sg_glmer_emmeans)

sg_glmer_pred <- predict(sg_glmer_emmeans, interval = "confidence", type = "response")

ggplot(sg_glmer_pred, aes(treatment, response)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
  facet_wrap(vars(era))

```



```{r}
# 
# pb_AICs <- lapply(list(pbe_gls_noac, pbe_gls_timeac, pbe_lme_no_ac, pbe_lme_timeac), FUN = AIC)
# pb_AICs
# 
# anova(pbe_gls_timeac, pbe_lme_timeac)
# 
# pb_emmeans <- emmeans(pbe_lme_timeac, specs = ~ treatment | era)
# 
# pairs(pb_emmeans, adjust = "bonf")
# 
# pb_gls_emmeans <- emmeans(pbe_gls_timeac, specs = ~ treatment | era)
# 
# pairs(pb_gls_emmeans, adjust = "bonf")
# 
# pb_pred <- predict(pb_gls_emmeans, interval = "confidence") 
# 
# ggplot(pb_pred, aes(treatment, emmean, color = treatment)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL)) +
#   facet_grid(cols = vars(era))
# 
# library(lme4)
# 
# pb_totals <- pb_totals %>%
#   mutate(scaled_pb_e = scale(pb_e))
# 
# pbe_lme_timeac_scaled <- lme(scaled_pb_e ~ treatment * era, random = ~1|plot, data = pb_totals, correlation = corCAR1(form = ~ numericdate | plot))
# 
# summary(pbe_lme_timeac_scaled)
# 
# pbe_lme_timeac_scaled_emmeans <- emmeans(pbe_lme_timeac_scaled, specs= ~ treatment | era)
# 
# pb_pred <- predict(pbe_lme_timeac_scaled_emmeans, interval = "confidence") 
# 
# unscale <- function(x) {
#  x *  attr(pb_totals$scaled_pb_e, 'scaled:scale') + attr(pb_totals$scaled_pb_e, 'scaled:center') 
# }
# 
# pb_pred_unscaled <- pb_pred %>%
#   mutate(emmean_unscaled = unscale(emmean) ,
#          lowerCL_unscaled = unscale(lower.CL),
#            upperCL_unscaled = unscale(upper.CL))
# 
# pb_means <- pb_totals %>%
#   group_by(plot, era, treatment) %>%
#   summarize(mean_e = mean(pb_e),
#             mean_scaled_e = mean(scaled_pb_e)) %>%
#   ungroup()
# 
# 
# ggplot(pb_means, aes(treatment, mean_scaled_e, color = treatment)) +
#   geom_point() +
#   facet_grid(cols = vars(era)) 
#   
# 
# ggplot(pb_pred, aes(treatment, emmean, color = treatment)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL)) +
#   facet_grid(cols = vars(era)) +
#   geom_point(data = pb_means, aes(treatment, mean_scaled_e), shape = 5)
# 
# 
# 
# ggplot(pb_pred_unscaled, aes(treatment, emmean_unscaled, color = treatment)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = lowerCL_unscaled, ymax = upperCL_unscaled)) +
#   facet_grid(cols = vars(era)) +
#   geom_point(data = pb_means, aes(treatment, mean_e), shape = 5)
# 
# pb_totals <- pb_totals %>%
#   mutate(pb_e = ceiling(pb_e))
# 
# pb_glm <- glm((pb_e) ~ treatment * era, data = pb_totals, family = "poisson")
# pb_glm_plot <- glm((pb_e) ~ treatment * era + plot, data = pb_totals, family = "poisson")
# pb_glm_plot_time <-  glm(pb_e ~ treatment * era + plot + numericdate, data = pb_totals, family = "poisson")
# 
# AIC(pb_glm)
# AIC(pb_glm_plot)
# AIC(pb_glm_plot_time)
# 
# summary(pb_glm_plot_time)
# 
# pairs(emmeans(pb_glm_plot_time, specs= ~ treatment | era))
# 
# pb_glm_emmeans <- (emmeans(pb_glm, specs= ~ treatment | era))
# 
# pb_glm_pred <- predict(pb_glm_emmeans, interval = "confidence")
# 
# ggplot(pb_glm_pred, aes(treatment, response, color = treatment)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
#   facet_grid(cols = vars(era))


pb_glmer <- glmer(ceiling(pb_e) ~ treatment * era + (1|plot), data =pb_totals, family = poisson)

pb_glmer_emmeans <- emmeans(pb_glmer, specs = ~  treatment | era)

pairs(pb_glmer_emmeans)

pb_glmer_pred <- predict(pb_glmer_emmeans, interval = "confidence", type = "response")

ggplot(pb_glmer_pred, aes(treatment, response)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
  facet_wrap(vars(era))

```


```{r}

tg_AICs <- lapply(list(tge_gls_noac, tge_gls_timeac, tge_lme_no_ac, tge_lme_timeac), FUN = AIC)
tg_AICs

anova(tge_gls_timeac, tge_lme_timeac)

tg_emmeans <- emmeans(tge_lme_timeac, specs = ~ treatment | era)

pairs(tg_emmeans, adjust = "bonf")

tg_gls_emmeans <- emmeans(tge_gls_timeac, specs = ~ treatment | era)

pairs(tg_gls_emmeans, adjust = "bonf")


tg_pred <- predict(tg_emmeans, interval = "confidence") 

ggplot(tg_pred, aes(treatment, emmean, color = treatment)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL)) +
  facet_grid(cols = vars(era))

tg_glmer <- glmer(ceiling(tinygran_e) ~ treatment * era + (1|plot), data =plot_totals, family = poisson)

tg_glmer_emmeans <- emmeans(tg_glmer, specs = ~  treatment | era)

pairs(tg_glmer_emmeans)

tg_glmer_pred <- predict(tg_glmer_emmeans, interval = "confidence", type = "response")

ggplot(tg_glmer_pred, aes(treatment, response)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL)) +
  facet_wrap(vars(era))

```