---
title: "Energy plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.dim = c(7, 3))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
source(here::here("scaffold", "R", "data.R"))
```

```{r}

use_christensen_plots <- F

library(mgcv)
source(here::here("lore", "1994_longterm", "gams_fxns_generalized.R"))

plot_totals <- get_rodent_data(use_christensen_plots = use_christensen_plots, return_plot = T) %>%
   mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

plot_annuals <- plot_totals %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot, plot_type, era) %>%
  summarize(annual_total_e = mean(total_e),
            annual_smgran_e = mean(smgran_e),
            annual_tinygran_e = mean(tinygran_e),
            nsamples = length(unique(period)),
            nrows = dplyr::n()) %>%
  ungroup()

treatment_means <- get_rodent_data(use_christensen_plots, F, F) %>%
  mutate(tinygran_e = smgran_e - pb_e) %>%
  mutate(oplottype = ordered(plot_type))

# treatment_ratios <- get_total_energy_ratios(treatment_means)

```

```{r}

treatment_annuals <- treatment_means %>%
  mutate(censusdate = as.Date(censusdate)) %>%
  mutate(censusyear = as.integer(format.Date(censusdate, "%Y"))) %>%
  group_by(censusyear, plot_type, era, nplots) %>%
  summarize(total_e = mean(total_e),
            dipo_e = mean(dipo_e),
            smgran_e = mean(smgran_e),
            pb_e = mean(pb_e),
            pp_e = mean(pp_e),
            tinygran_e = mean(tinygran_e),
            nsamples = dplyr::n(),
            nperiods = length(unique(period))) %>%
  ungroup()

```

```{r}


ggplot(treatment_annuals, aes(censusyear, total_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)


ggplot(treatment_annuals, aes(censusyear, smgran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)


ggplot(treatment_annuals, aes(censusyear, tinygran_e, color = plot_type)) +
  geom_line() +
  scale_color_viridis_d(end = .8)

```

```{r}
sg_e_mod <- gam(smgran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

sg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "smgran")

sg_e_pred <- get_predicted_vals(sg_e_mod, sg_e_pdat)

plot_fitted_pred(sg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(sg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(sg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(sg_e_mod, sg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(sg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```


```{r}
tg_e_mod <- gam(tinygran_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

tg_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "tinygran")

tg_e_pred <- get_predicted_vals(tg_e_mod, tg_e_pdat)

plot_fitted_pred(tg_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(tg_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(tg_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(tg_e_mod, tg_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(tg_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```


```{r}
total_e_mod <- gam(total_e ~ oplottype + s(period, k = 20) + s(period, by = oplottype, k = 20), family = "tw", data = treatment_means)

total_e_pdat <- treatment_means %>%
  select(period, oplottype) %>%
  mutate(type = "all_energy")

total_e_pred <- get_predicted_vals(total_e_mod, total_e_pdat)

plot_fitted_pred(total_e_pred, comparison_variable = "oplottype")

ee_cc_diff <- get_exclosure_diff(total_e_mod, total_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 3)
ee_cc_pred <- add_exclosure_diff(total_e_pred, ee_cc_diff)
plot_fitted_pred(filter(ee_cc_pred, oplottype != "CE"), comparison_variable = "oplottype")


ce_cc_diff <- get_exclosure_diff(total_e_mod, total_e_pdat,comparison_variable = "oplottype", reference_level = 1, comparison_level = 2)
ce_cc_pred <- add_exclosure_diff(total_e_pred, ce_cc_diff)
plot_fitted_pred(filter(ce_cc_pred, oplottype != "EE"), comparison_variable = "oplottype") + scale_color_viridis_d(end = .4) + scale_fill_viridis_d(end = .4)

ee_ce_diff <- get_exclosure_diff(total_e_mod, total_e_pdat,comparison_variable = "oplottype", reference_level = 2, comparison_level = 3)
ee_ce_pred <- add_exclosure_diff(total_e_pred, ee_ce_diff)
plot_fitted_pred(filter(ee_ce_pred, oplottype != "CC"), comparison_variable = "oplottype")+ scale_color_viridis_d(begin = .4, end = .8) + scale_fill_viridis_d(begin = .4, end = .8)
```

## Ratios


```{r}
treatment_ratios <- get_total_energy_ratios(treatment_means) %>%
  mutate(sg_of_c = smgran_e / total_e_c,
         tg_of_c = tinygran_e / total_e_c) %>%
  mutate(total_e_of_c = 0.0000000001 + total_e_of_c,
         sg_of_c = 0.0000000001 + sg_of_c,
         tg_of_c = 0.0000000001 + tg_of_c) %>%
  mutate(fplottype = factor(plot_type))

```


```{r}

sg_ratio_gam <- gam(sg_of_c ~ fplottype + s(period, k = 40) + s(period, by = fplottype, k = 40), family = "Gamma", data = treatment_ratios)

sg_ratio_pdat <- select(treatment_ratios, fplottype, period) %>%
  mutate(type = "sgmran")

sg_ratio_pred <- get_predicted_vals(sg_ratio_gam, sg_ratio_pdat)

plot_fitted_pred(filter(sg_ratio_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) 
# +
#   scale_color_viridis_d(begin = .8, end = .8) +
#   scale_fill_viridis_d(begin = .8, end = .8)


```


```{r}

tg_ratio_gam <- gam(tg_of_c ~ fplottype + s(period, k = 40) + s(period, by = fplottype, k = 40), family = "Gamma", data = treatment_ratios)

tg_ratio_pdat <- select(treatment_ratios, fplottype, period) %>%
  mutate(type = "tinygran")

tg_ratio_pred <- get_predicted_vals(tg_ratio_gam, tg_ratio_pdat)

plot_fitted_pred(filter(tg_ratio_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1) 
# +
#   scale_color_viridis_d(begin = .8, end = .8) +
#   scale_fill_viridis_d(begin = .8, end = .8)



```

```{r}

total_ratio_gam <- gam(total_e_of_c ~ fplottype + s(period, k = 40) + s(period, by = fplottype, k = 40), family = "Gamma", data = filter(treatment_ratios, fplottype != "CC"))

total_ratio_pdat <- select(treatment_ratios, fplottype, period) %>%
  mutate(type = "all_energy") %>%
  filter(fplottype != "CC")

total_e_pred <- get_predicted_vals(total_ratio_gam, total_ratio_pdat)

plot_fitted_pred(filter(total_e_pred, fplottype != "CE"), comparison_variable = "fplottype") +
  geom_hline(yintercept = 1)  +
  scale_color_viridis_d(begin = .8, end = .8) +
  scale_fill_viridis_d(begin = .8, end = .8)

```

## By era

```{r}

era_means <- treatment_means %>%
  group_by(era, plot_type) %>%
  mutate(total_e_mean = mean(total_e),
         smgran_e_mean = mean(smgran_e),
         tinygran_e_mean = mean(tinygran_e)) %>%
  ungroup()

ggplot(era_means, aes(period, total_e_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, total_e), alpha = .3) +
  scale_color_viridis_d(end = .8)


ggplot(era_means, aes(period, smgran_e_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, smgran_e), alpha = .3) +
  scale_color_viridis_d(end = .8)



ggplot(era_means, aes(period, tinygran_e_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, tinygran_e), alpha = .3) +
  scale_color_viridis_d(end = .8)

select(era_means, era, oplottype, total_e_mean, smgran_e_mean, tinygran_e_mean) %>%
  distinct()

```

### gls on actual vals

```{r}

library(nlme)
library(lsmeans)

te_gls <- gls(total_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
#summary(pairs(lsmeans(te_gls, specs = ~oplottype | era)))

sg_gls <- gls(smgran_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
summary(pairs(lsmeans(sg_gls, specs = ~oplottype | era)))

tg_gls <- gls(tinygran_e ~ era * oplottype, data = treatment_means, correlation = corAR1(form = ~period|oplottype))
summary(pairs(lsmeans(tg_gls, specs = ~oplottype | era)))


```

### gls on ratios

```{r}

era_ratios <- treatment_ratios %>%
  group_by(era, oplottype) %>%
  mutate(te_mean = mean(total_e_of_c),
         sg_mean = mean(sg_of_c),
         tg_mean = mean(tg_of_c)) %>%
  ungroup()


ggplot(era_ratios, aes(period, te_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, total_e_of_c), alpha = .3) +
  scale_color_viridis_d(end = .8)


ggplot(era_ratios, aes(period, sg_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, sg_of_c), alpha = .3) +
  scale_color_viridis_d(end = .8)



ggplot(era_ratios, aes(period, tg_mean, color = oplottype)) +
  geom_line(size = 2) +
  geom_line(aes(period, tg_of_c), alpha = .3) +
  scale_color_viridis_d(end = .8)


treatment_ratios_no_c <- filter(treatment_ratios, fplottype != "CC")

ter_gls <- gls(total_e_of_c ~ era * fplottype, data = treatment_ratios_no_c, correlation = corAR1(form = ~period|fplottype))
#summary(pairs(lsmeans(ter_gls, specs = ~fplottype | era)))

sgr_gls <- gls(sg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype))
summary(pairs(lsmeans(sgr_gls, specs = ~fplottype | era)))

tgr_gls <- gls(tg_of_c ~ era * fplottype, data = treatment_ratios, correlation = corAR1(form = ~period|fplottype))
summary(pairs(lsmeans(tgr_gls, specs = ~fplottype | era)))

```