---
title: "Plot variability"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.dim = c(6, 3))
library(soar)
library(ggplot2)
library(dplyr)
library(gratia)
library(emmeans)
theme_set(theme_bw())
```

Wondering if maybe controls are less variable between-plots than other treatment types. That would make it more OK to compare plot-level values for other treatments to a control-level mean.

```{r}

plotl <- get_plot_totals()

```


# total e

```{r}
ggplot(plotl, aes(censusdate, total_e_ma, color = fplot)) +
  geom_line() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = 'none')

plot_resid <- plotl %>%
  group_by(oplottype, period) %>%
  mutate(period_mean_totale = mean(total_e),
         period_sd_totale = sd(total_e)) %>%
  ungroup() %>%
  mutate(total_e_resid = total_e - period_mean_totale,
         total_e_scaled_sd = period_sd_totale / period_mean_totale)

ggplot(plot_resid, aes(censusdate, total_e_resid, color = fplot)) +
  geom_point() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = "none")

ggplot(plot_resid, aes(censusdate, total_e_scaled_sd)) +
  geom_line() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = "none")

load_mgcv()
resid_gam <- gam(total_e_scaled_sd ~ fplottype + s(period) + s(period, by = fplottype), data = plot_resid)

summary(resid_gam)

plot_resid_pred <- plot_resid %>%
  add_fitted(resid_gam, value = "fit")



ggplot(plot_resid_pred, aes(censusdate, fit, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(oplottype)) +
  theme(legend.position = "top")


era_mean_scaled_sd <- plot_resid %>%
  group_by(oplottype, oera) %>%
  summarize(mean_total_e_sd = mean(total_e_scaled_sd, na.rm = T)) %>%
  ungroup()


ggplot(era_mean_scaled_sd, aes(oera, mean_total_e_sd, color = oplottype)) +
  geom_point()

```


## smgran e

is actually more variable between-plots on controls than on treatments. I think. this is sketchy. 

```{r}

ggplot(plotl, aes(censusdate, smgran_e_ma, color = fplot)) +
  geom_line() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = 'none')

plot_resid <- plotl %>%
  group_by(oplottype, period) %>%
  mutate(period_mean_totale = mean(smgran_e),
         period_sd_totale = sd(smgran_e)) %>%
  ungroup() %>%
  mutate(smgran_e_resid = smgran_e - period_mean_totale,
         smgran_e_scaled_sd = period_sd_totale / period_mean_totale)

ggplot(plot_resid, aes(censusdate, smgran_e_resid, color = fplot)) +
  geom_point() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = "none")

ggplot(plot_resid, aes(censusdate, smgran_e_scaled_sd)) +
  geom_line() +
  facet_wrap(vars(oplottype)) +
  theme(legend.position = "none")

load_mgcv()
resid_gam <- gam(smgran_e_scaled_sd ~ fplottype + s(period) + s(period, by = fplottype), data = plot_resid)

summary(resid_gam)

plot_resid_pred <- plot_resid %>%
  add_fitted(resid_gam, value = "fit")



ggplot(plot_resid_pred, aes(censusdate, fit, color = oplottype)) +
  geom_line() +
  #facet_wrap(vars(oplottype)) +
  theme(legend.position = "top")


era_mean_scaled_sd <- plot_resid %>%
  group_by(oplottype, oera) %>%
  summarize(mean_smgran_e_sd = mean(smgran_e_scaled_sd, na.rm = T)) %>%
  ungroup()


ggplot(era_mean_scaled_sd, aes(oera, mean_smgran_e_sd, color = oplottype)) +
  geom_point()

```